[build]
  publish = "_site"
  command = "npx @11ty/eleventy"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  framework = "#custom"
  command = "npx @11ty/eleventy --serve --port 5000"
  targetPort = 5000
  port = 8888
  publish = "_site"
  autoLaunch = false