module.exports = function () {
  // Helper function to parse auctionStartDateTime
  function parseAuctionDate(dateStr) {
    if (!dateStr) return null;
    // DDMMYYYY:HH:MM:SS
    const day = dateStr.substring(0, 2);
    const month = dateStr.substring(2, 4); // Month is 0-indexed in JS Date constructor if using YYYY,MM,DD
    const year = dateStr.substring(4, 8);
    const time = dateStr.substring(9); // HH:MM:SS
    // Ensure consistent date string format for Date constructor (YYYY-MM-DDTHH:MM:SS)
    return new Date(`${year}-${month}-${day}T${time}`);
  }

  // Filter function to remove past auctions
  function filterUpcomingAuctions(auctionsList) {
    const now = new Date();
    return auctionsList.filter(auction => {
      const auctionDate = parseAuctionDate(auction.auctionStartDateTime);
      return auctionDate && auctionDate >= now;
    }).sort((a, b) => {
      // Sort by date ascending (earliest first)
      const dateA = parseAuctionDate(a.auctionStartDateTime);
      const dateB = parseAuctionDate(b.auctionStartDateTime);
      return dateA - dateB;
    });
  }

  // TODO: Future integration options
  // 1. Fetch from CMS API (Strapi, Contentful, etc.)
  // 2. Web scraping from auction house websites
  // 3. RSS/JSON feeds from auction houses
  // 4. Manual CSV/JSON file updates
  // 
  // Example CMS integration:
  // const fetchAuctionsFromCMS = async () => {
  //   try {
  //     const response = await fetch('https://your-cms.com/api/auctions?status=upcoming');
  //     const cmsAuctions = await response.json();
  //     return cmsAuctions.map(auction => ({
  //       // Transform CMS data to your format
  //     }));
  //   } catch (error) {
  //     console.log('Failed to fetch from CMS, using static data');
  //     return [];
  //   }
  // };

  // This would typically be fetched from a headless CMS
  // For now, using static data based on the provided sample
  const auctions = [
    // ============ ANGLIA CAR AUCTIONS ============
    {
      auctionTitle: "June 2025 Classic Car Auction",
      auctionStartDateTime: "14062025:09:00:00",
      auctionWebsite: "https://angliacarauctions.co.uk/auctions/2706-14-Jun-2025",
      auctionAddress: "The Cattle Market, Beveridge Way, King's Lynn, Norfolk",
      auctionLat: 52.733709,
      auctionLng: 0.411435,
      auctionPhone: "01553 771881",
      auctionCity: "King's Lynn",
      auctionPostalCode: "PE30 4NB",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/anglia-car-auctions-june-2025.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Norfolk",
      auctionSlug: "june-2025-classic-car-auction",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars, Motorcycles and Automobilia",
      auctionHighlightsHtml: "Classic Car Auction featuring a wide range of vehicles<br>Automobilia from 10am Saturday<br>Motorcycles from 10am Sunday<br>Two-day auction event",
      auctionHouse: "Anglia Car Auctions"
    },

    // ============ BRIGHTWELLS ============
    {
      auctionTitle: "25th June 2025 Classic Cars & Motorcycles",
      auctionStartDateTime: "25062025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-june-2025-classic-cars.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-june-2025-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars and Motorcycles Auction",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Viewing available Monday-Tuesday before auction<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "25th June 2025 Modern Classics",
      auctionStartDateTime: "25062025:14:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-june-2025-modern-classics.avif",
      auctionCategory: "Modern Classics Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-june-2025-modern-classics",
      auctionFeatured: false,
      auctionHighlights: "Modern Classic Car Auction",
      auctionHighlightsHtml: "Timed online auction featuring modern classics<br>Bidding starts Saturday before auction<br>Viewing Monday-Tuesday prior to auction",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "6th August 2025 Classic Cars & Motorcycles",
      auctionStartDateTime: "06082025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-august-2025-classic-cars.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-august-2025-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars and Motorcycles Auction",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Vehicles physically present at Easters Court premises<br>Extensive vehicle inspection and paperwork verification",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "6th August 2025 Modern Classics",
      auctionStartDateTime: "06082025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-august-2025-modern-classics.avif",
      auctionCategory: "Modern Classics Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-august-2025-modern-classics",
      auctionFeatured: false,
      auctionHighlights: "Modern Classic Car Auction",
      auctionHighlightsHtml: "Timed online auction specialising in modern classics.<br> Online bidding format with extensive preparation time",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "17th September 2025 Classic Cars & Motorcycles",
      auctionStartDateTime: "17092025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-september-2025-classic-cars.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-september-2025-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars and Motorcycles Auction",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Viewing available Monday-Tuesday before auction<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "29th October 2025 Classic Cars & Motorcycles",
      auctionStartDateTime: "29102025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-october-2025-classic-cars.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-october-2025-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars and Motorcycles Auction",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Viewing available Monday-Tuesday before auction<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "29th October 2025 Modern Classics",
      auctionStartDateTime: "29102025:14:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-october-2025-modern-classics.avif",
      auctionCategory: "Modern Classics Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-october-2025-modern-classics",
      auctionFeatured: false,
      auctionHighlights: "Modern Classic Car Auction",
      auctionHighlightsHtml: "Timed online auction specialising in modern classics. <br>Online bidding format with extensive preparation time",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "10th December 2025 Classic Cars & Motorcycles",
      auctionStartDateTime: "10122025:10:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-december-2025-classic-cars.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-december-2025-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars and Motorcycles Auction",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Viewing available Monday-Tuesday before auction<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "10th December 2025 Modern Classics",
      auctionStartDateTime: "10122025:14:00:00",
      auctionWebsite: "https://www.brightwells.com/classic-motoring/catalogue-not-available/",
      auctionAddress: "Easters Court, Mill Street, Leominster",
      auctionLat: 52.2316809,
      auctionLng: -2.7332604,
      auctionPhone: "01568 611122",
      auctionCity: "Leominster",
      auctionPostalCode: "HR6 0DE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/brightwells-december-2025-modern-classics.avif",
      auctionCategory: "Modern Classics Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-december-2025-modern-classics",
      auctionFeatured: false,
      auctionHighlights: "Modern Classic Car Auction",
      auctionHighlightsHtml: "Timed online auction specializing in modern classics<br>£2,500 registration deposit required to participate<br>Online bidding format with extensive preparation time",
      auctionHouse: "Brightwells"
    },

    // ============ CAR & CLASSIC AUCTIONS ============
    // No auctions listed for Car & Classic Auctions in your data

    // ============ CHARTERHOUSE ============
    // No auctions listed for Charterhouse in your data

    {
      auctionTitle: "Classic & Vintage Car Auction",
      auctionStartDateTime: "26062025:11:00:00",
      auctionWebsite: "https://charterhouse-cars.com/next-car-auction",
      auctionAddress: "Haynes International Motor Museum, Sparkford",
      auctionLat: 51.0408941,
      auctionLng: -2.5602764,
      auctionPhone: "01935 812277",
      auctionCity: "Yeovil",
      auctionPostalCode: "BA22 7LH",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/charterhouse-june-2025-classic-car-auction.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Somerset",
      auctionSlug: "charterhouse-june-2025-classic-vintage-car-auction",
      auctionFeatured: false,
      auctionHighlights: "Sir Malcolm Campbell's 1946 Armstrong Siddeley Hurricane",
      auctionHighlightsHtml: "Sir Malcolm Campbell's 1946 Armstrong Siddeley Hurricane<br>Painted in Campbell's special 'Blue Bird' colour<br>Estimated to sell for £10,000-£15,000",
      auctionHouse: "Charterhouse"
    },

    

    // ============ DORE & REES ============
{
  auctionTitle: "Thruxton Retro Competition and Fast Road Cars, and Motorcycles",
  auctionStartDateTime: "21062025:11:00:00",
  auctionWebsite: "https://www.doreandrees.com/motoring",
  auctionAddress: "Thruxton Circuit, Andover",
  auctionLat: 51.2060635,
  auctionLng: -1.6114635,
  auctionPhone: "07920 500091",
  auctionCity: "Andover",
  auctionPostalCode: "SP11 8PN",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/dore-rees-thruxton-june-2025.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "Hampshire",
  auctionSlug: "dore-rees-thruxton-retro-competition-cars-june-2025",
  auctionFeatured: false,
  auctionHighlights: "Competition and Fast Road Cars, and Motorcycles Auction",
  auctionHighlightsHtml: "Competition and Fast Road Cars, and Motorcycles<br>Held at Thruxton Circuit - the UK's fastest race circuit<br>Part of the Thruxton Retro racing festival",
  auctionHouse: "Dore & Rees"
},
{
  auctionTitle: "Castle Combe Autumn Classic",
  auctionStartDateTime: "21092025:11:00:00",
  auctionWebsite: "https://www.doreandrees.com/motoring",
  auctionAddress: "Castle Combe Circuit, Castle Combe, Chippenham",
  auctionLat: 51.4937077,
  auctionLng: -2.2169342,
  auctionPhone: "07920 500091",
  auctionCity: "Chippenham",
  auctionPostalCode: "SN14 7EY",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/dore-rees-castle-combe-september-2025.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "Wiltshire",
  auctionSlug: "dore-rees-castle-combe-autumn-classic-september-2025",
  auctionFeatured: false,
  auctionHighlights: "Collector's Cars Auction at Castle Combe Autumn Classic",
  auctionHighlightsHtml: "Classic and collector's car auction<br>Held at the historic Castle Combe Circuit<br>Part of the Castle Combe Autumn Classic event",
  auctionHouse: "Dore & Rees"
},


    





    // ============ DVCA ============
    // No auctions listed for DVCA in your data

    // ============ EWBANK'S ============
    {
      auctionTitle: "Summer Classic & Modern Cars & Automobilia",
      auctionStartDateTime: "04072025:10:00:00",
      auctionWebsite: "https://www.ewbankauctions.co.uk/Classic-Modern-Cars-Automobilia/2025-07-04",
      auctionAddress: "Burnt Common Auction Rooms, London Road, Send, Woking, Surrey, GU23 7LN, UK",
      auctionLat: 51.2776867,
      auctionLng: -0.5225828,
      auctionPhone: "01483 223101",
      auctionCity: "Woking",
      auctionPostalCode: "GU23 7LN",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/ewbank-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Surrey",
      auctionSlug: "classic-modern-cars-automobilia-july-2025",
      auctionFeatured: false,
      auctionHighlights: "Classic and modern cars, vintage car mascots, automobilia including toy models, period prints, signs, petroliana, brochures and parts",
      auctionHighlightsHtml: "Surrey's premier classic car auction featuring vehicles from brands including Bentley, Ferrari, Alfa Romeo, Mercedes-Benz, McLaren, Jaguar, Austin Healey, and Rolls Royce.",
      auctionHouse: "Ewbank's"
    },

    {
      auctionTitle: "Autumn Cars, Motorbikes & Automobilia",
      auctionStartDateTime: "03102025:10:00:00",
      auctionWebsite: "https://www.ewbankauctions.co.uk/Classic-Modern-Cars-Automobilia/2025-07-04",
      auctionAddress: "Burnt Common Auction Rooms, London Road, Send, Woking, Surrey, GU23 7LN, UK",
      auctionLat: 51.2776867,
      auctionLng: -0.5225828,
      auctionPhone: "01483 223101",
      auctionCity: "Woking",
      auctionPostalCode: "GU23 7LN",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/ewbank-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Surrey",
      auctionSlug: "ewbanks-classic-modern-cars-automobilia-october-2025",
      auctionFeatured: false,
      auctionHighlights: "Classic and modern cars, vintage car mascots, automobilia including toy models, period prints, signs, petroliana, brochures and parts",
      auctionHighlightsHtml: "Surrey's premier classic car auction featuring vehicles from brands including Bentley, Ferrari, Alfa Romeo, Mercedes-Benz, McLaren, Jaguar, Austin Healey, and Rolls Royce.",
      auctionHouse: "Ewbank's"
    },

    // ============ H&H CLASSICS ============
    {
      auctionTitle: "Pavilion Gardens Buxton Classic Motors Auction",
      auctionStartDateTime: "21052025:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "St John's Rd, Buxton, SK17 6BE, UK",
      auctionLat: 53.2617,
      auctionLng: -1.9126,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Buxton",
      auctionPostalCode: "SK17 6BE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/handh/pavilion-gardens-buxton-classic-motors-auction-may-2025.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Derbyshire",
      auctionSlug: "pavilion-gardens-buxton-classic-motors-auction-may-2025",
      auctionFeatured: false,
      auctionHighlights: "Beautiful Pavilion Gardens setting - 137 lots of classic, collector and performance motorcars",
      auctionHighlightsHtml: "1953 Bentley R-Type 'Le Mans' Style Open Tourer by Paul Forty <br> 1960 Maserati 3500 GT <br> 1950 Healey Silverstone D-Type <br> +134 more...",
      auctionHouse: "H&H Classics"
    },
    {
      auctionTitle: "Millbrook Proving Ground Classic Motors Auction",
      auctionStartDateTime: "25062025:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "Station Lane, Bedford, MK45 2JQ, UK",
      auctionLat: 52.0678,
      auctionLng: -0.5568,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Milton Keynes",
      auctionPostalCode: "MK45 2JQ",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/handh/millbrook-proving-ground-classic-motors-auction-june-2025.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Buckinghamshire",
      auctionSlug: "millbrook-proving-ground-classic-motors-auction-june-2025",
      auctionFeatured: false,
      auctionHighlights: "1957 Bentley S1 Continental HJ Mulliner Fastback / 1971 Aston Martin DBS V8 / 1964 Rolls-Royce Silver Cloud III Drophead Coupe",
      auctionHighlightsHtml: "1957 Bentley S1 Continental HJ Mulliner Fastback<br>1971 Aston Martin DBS V8<br>1964 Rolls-Royce Silver Cloud III Drophead Coupe",
      auctionHouse: "H&H Classics"
    },

    // ============ HAMPSON MARKPLACE ============
    {
      auctionTitle: "The Gold Cup 2025 Classic, Performance & Supercar Auction",
      auctionStartDateTime: "27072025:12:00:00",
      auctionWebsite: "https://auctions.hampsonauctions.com/auction/details/-the-gold-cup-2025-classic-performance--supercar-auction/?au=31",
      auctionAddress: "Oulton Park Circuit, Little Budworth, Tarporley, Cheshire, CW6 9BW, UK",
      auctionLat: 53.1770869,
      auctionLng: -2.6223099,
      auctionPhone: "01606 828124",
      auctionCity: "Tarporley",
      auctionPostalCode: "CW6 9BW",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "gold-cup-2025-classic-performance-supercar-auction",
      auctionFeatured: false,
      auctionHighlights: "Live auction at the prestigious Oulton Park Gold Cup Weekend featuring classic cars, performance vehicles, supercars, motorcycles, registrations and automobilia",
      auctionHighlightsHtml: "Live auction at the prestigious Oulton Park Gold Cup Weekend featuring classic cars, performance vehicles, supercars, motorcycles, registrations and automobilia. <br>Viewing: <br>Friday 25th July 9am-6pm, <br>Saturday 26th July 12noon-6pm, <br>Sunday 27th July 9am-12noon. <br>Auction charges among the lowest in the industry.",
      auctionHouse: "Hampson Marketplace"
    },

    {
      auctionTitle: "The Bolesworth Castle September 2025 Classic, Performance & Supercar Auction",
      auctionStartDateTime: "28092025:12:00:00",
      auctionWebsite: "https://auctions.hampsonauctions.com/auction/details/-the-bolesworth-castle-september-2025-classic-performance--supercar-auction/?au=32",
      auctionAddress: "Bolesworth Castle, Tattenhall, Chester, Cheshire, CH3 9HQ, UK",
      auctionLat: 53.1337194,
      auctionLng: -2.9666355,
      auctionPhone: "01606 828124",
      auctionCity: "Chester",
      auctionPostalCode: "CH3 9HQ",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "bolesworth-castle-september-2025-classic-performance-supercar-auction",
      auctionFeatured: false,
      auctionHighlights: "Auction at the stunning Grade II* listed Bolesworth Castle featuring classic and collector cars, supercars, competition cars, motorcycles and automobilia",
      auctionHighlightsHtml: "Live auction at the magnificent Bolesworth Castle, a Grade II* listed country house set in 6,000 acres of beautiful Cheshire countryside. <br>Viewing: <br>Saturday 27th September 12noon-6pm, <br>Sunday 28th September 9am-12noon. <br>Buyer's Premium: Motor Cars 12.5% + VAT (min £250 + VAT), Registration Numbers 15% + VAT, Automobilia 15% + VAT.",
      auctionHouse: "Hampson Marketplace"
    },

    // ============ HISTORICS ============
    // No auctions listed for Historics in your data

    // ============ HUMBERT & ELLIS ============
    // No auctions listed for Humbert & Ellis in your data

   // ============ ICONIC AUCTIONEERS ============
{
  auctionTitle: "The Classic Sale at Wheeler Dealer Live 2025",
  auctionStartDateTime: "01062025:11:00:00",
  auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
  auctionAddress: "Bicester Motion",
  auctionLat: 51.9160,
  auctionLng: -1.1409,
  auctionPhone: "01926 691141",
  auctionCity: "Bicester",
  auctionPostalCode: "OX26 5HA",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/iconic-auctioneers-wheeler-dealer-june-2025.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "Oxfordshire",
  auctionSlug: "iconic-auctioneers-wheeler-dealer-live-june-2025",
  auctionFeatured: false,
  auctionHighlights: "148 Entries of Classic and Vintage Cars",
  auctionHighlightsHtml: "148 Classic and Vintage Car Entries<br>Live auction with in-person and online bidding<br>Viewing available Saturday 31st May",
  auctionHouse: "Iconic Auctioneers"
},
{
  auctionTitle: "The Silverstone Classic Sale - Day 1",
  auctionStartDateTime: "23082025:11:00:00",
  auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
  auctionAddress: "The Wing, Silverstone Circuit",
  auctionLat: 52.0786,
  auctionLng: -1.0147,
  auctionPhone: "01926 691141",
  auctionCity: "Silverstone",
  auctionPostalCode: "NN12 8TN",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/iconic-auctioneers-silverstone-august-2025-day1.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "Northamptonshire",
  auctionSlug: "iconic-auctioneers-silverstone-classic-august-2025-day1",
  auctionFeatured: false,
  auctionHighlights: "Classic Car Auction at the Historic Silverstone Circuit",
  auctionHighlightsHtml: "Premier classic car auction at Silverstone Circuit<br>Held at The Wing building<br>In-person and online bidding available",
  auctionHouse: "Iconic Auctioneers"
},
{
  auctionTitle: "The Silverstone Classic Sale - Day 2",
  auctionStartDateTime: "24082025:11:00:00",
  auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
  auctionAddress: "The Wing, Silverstone Circuit",
  auctionLat: 52.0786,
  auctionLng: -1.0147,
  auctionPhone: "01926 691141",
  auctionCity: "Silverstone",
  auctionPostalCode: "NN12 8TN",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/iconic-auctioneers-silverstone-august-2025-day2.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "Northamptonshire",
  auctionSlug: "iconic-auctioneers-silverstone-classic-august-2025-day2",
  auctionFeatured: false,
  auctionHighlights: "Day 2 of the Prestigious Silverstone Classic Car Auction",
  auctionHighlightsHtml: "Second day of the premier classic car auction<br>Held at The Wing building at Silverstone Circuit<br>Multiple bidding options including in-person, phone, and online",
  auctionHouse: "Iconic Auctioneers"
},
{
  auctionTitle: "The NEC Classic Motor Show Sale",
  auctionStartDateTime: "07112025:11:00:00",
  auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
  auctionAddress: "NEC, Birmingham",
  auctionLat: 52.4510,
  auctionLng: -1.7235,
  auctionPhone: "01926 691141",
  auctionCity: "Birmingham",
  auctionPostalCode: "B40 1NT",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/iconic-auctioneers-nec-november-2025.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "West Midlands",
  auctionSlug: "iconic-auctioneers-nec-classic-motor-show-november-2025",
  auctionFeatured: false,
  auctionHighlights: "Classic Car Auction at the UK's Biggest Classic Motor Show",
  auctionHighlightsHtml: "One of Iconic Auctioneers' biggest annual classic car auctions<br>Part of the NEC Classic Motor Show<br>Wide range of prestigious classic and collector vehicles",
  auctionHouse: "Iconic Auctioneers"
},
{
  auctionTitle: "The NEC Classic Motor Show Sale - Day 2",
  auctionStartDateTime: "08112025:11:00:00",
  auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
  auctionAddress: "NEC, Birmingham",
  auctionLat: 52.4510,
  auctionLng: -1.7235,
  auctionPhone: "01926 691141",
  auctionCity: "Birmingham",
  auctionPostalCode: "B40 1NT",
  auctionCountryCode: "GB",
  auctionImageUrl: "/assets/images/auctions/iconic-auctioneers-nec-november-2025-day2.avif",
  auctionCategory: "Classic Car Auctions",
  auctionState: "West Midlands",
  auctionSlug: "iconic-auctioneers-nec-classic-motor-show-november-2025-day2",
  auctionFeatured: false,
  auctionHighlights: "Day 2 of the NEC Classic Motor Show Auction",
  auctionHighlightsHtml: "Second day of the premier NEC Classic Motor Show auction<br>Access with £20 auction catalogue (admits two)<br>Additional classic cars and automobilia",
  auctionHouse: "Iconic Auctioneers"
},

    // ============ MANOR PARK CLASSICS ============
    {
      auctionTitle: "May 2025 Motorcycle Auction",
      auctionStartDateTime: "23052025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/manor-park-may-2025-motorcycle-auction.avif",
      auctionCategory: "Classic Motorcycle Auctions",
      auctionState: "Cheshire",
      auctionSlug: "may-2025-motorcycle-auction",
      auctionFeatured: false,
      auctionHighlights: "1990 Ducati 900 SS - Estimate: £8,500 - £9,500",
      auctionHighlightsHtml: "1990 Ducati 900 SS <br> 1984 Yamaha RZV500R <br> 1956 BSA DBD34 Gold Star <br> +61 More...",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "May 2025 Classic Car Auction",
      auctionStartDateTime: "24052025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/manor-park-may-2025-classic-car-auction.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "may-2025-classic-car-auction",
      auctionFeatured: false,
      auctionHighlights: "2003 Land Rover Discovery 4.0i V8 ES - Estimate: £13,000 - £15,000",
      auctionHighlightsHtml: "1965 Jaguar E-Type 4.2 Coupe <br> 2009 Ferrari F430 F1 <br> 1936 Bentley 4.25 Litre Tourer <br> +107 more...",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "Southampton Classic Car & Motorcycle Auction",
      auctionStartDateTime: "14062025:13:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton, SO40 4AF, UK",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "southampton-classic-car-motorcycle-auction",
      auctionFeatured: false,
      auctionHighlights: "1997 Ducati 996 SPS - Estimate: £17,000 - £19,000",
      auctionHighlightsHtml: "1997 Ducati 996 SPS - Estimate: £17,000 - £19,000",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "July 2025 Classic Car Auction",
      auctionStartDateTime: "26072025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "july-2025-classic-car-auction",
      auctionFeatured: false,
      auctionHighlights: "1983 Ford Cortina 3.0 S Evocation - Estimate: £8,500 - £9,500",
      auctionHighlightsHtml: "Preview available soon",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "September 2025 Classic Car & Motorcycle Auction",
      auctionStartDateTime: "27092025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "september-2025-classic-car-motorcycle-auction",
      auctionFeatured: false,
      auctionHighlights: "1984 Yamaha RZV500R - Estimate: £13,000 - £15,000",
      auctionHighlightsHtml: "Preview available soon",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "October 2025 Classic Car Auction",
      auctionStartDateTime: "25102025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.367891,
      auctionLng: -2.713139,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "october-2025-classic-car-auction",
      auctionFeatured: false,
      auctionHighlights: "1956 BSA DBD34 Gold Star - Estimate: £9,000 - £11,000",
      auctionHighlightsHtml: "Preview available soon",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "December 2025 Christmas Auction",
      auctionStartDateTime: "13122025:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire, WA7 1TA, UK",
      auctionLat: 53.367891,
      auctionLng: -2.713139,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "december-2025-christmas-auction",
      auctionFeatured: false,
      auctionHighlights: "1947 Matchless G3L - Estimate: £2,990 - £3,500",
      auctionHighlightsHtml: "Preview available soon",
      auctionHouse: "Manor Park Classics"
    },

    // ============ MATHEWSONS ============
    {
      auctionTitle: "June Classic Vehicles & Memorabilia Auction",
      auctionStartDateTime: "25062025:10:00:00",
      auctionWebsite: "https://www.mathewsons.co.uk/auction/details/-june-classic-vehicles--memorabilia-auction/?au=104",
      auctionAddress: "10 Enterprise Way, Thornton Road, Pickering, North Yorkshire",
      auctionLat: 54.2370631,
      auctionLng: -0.7645434,
      auctionPhone: "01751 474455",
      auctionCity: "Pickering",
      auctionPostalCode: "YO18 7NA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auctions/mathewsons-june-2025-classic-vehicles.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "North Yorkshire",
      auctionSlug: "june-2025-classic-vehicles-memorabilia-auction",
      auctionFeatured: false,
      auctionHighlights: "Classic Vehicles and Automobilia Memorabilia",
      auctionHighlightsHtml: "Three-day classic vehicle auction<br>Wednesday (Lots 1-300)<br>Thursday (Lots 301-600)<br>Friday (Lots 601-900)",
      auctionHouse: "Mathewsons"
    },

    // ============ MORRIS LESLIE ============
    // No auctions listed for Morris Leslie in your data

    // ========================================================================
    // ============ 2026 AUCTIONS (25 May 2026 – 31 December 2026) ============
    // ========================================================================

    // ---- MAY 2026 ----
    {
      auctionTitle: "May 2026 Timed Auction",
      auctionStartDateTime: "26052026:20:00:00",
      auctionWebsite: "https://www.mathewsons.co.uk/auction/details/-may-timed-auction?au=123",
      auctionAddress: "Unit 10, Enterprise Way, Thornton Road, Pickering, North Yorkshire",
      auctionLat: 54.2370631,
      auctionLng: -0.7645434,
      auctionPhone: "01751 474455",
      auctionCity: "Pickering",
      auctionPostalCode: "YO18 7NA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/mathewsons-auction-house-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "North Yorkshire",
      auctionSlug: "mathewsons-may-2026-timed-auction",
      auctionFeatured: false,
      auctionHighlights: "Online Timed Classic Vehicle Auction",
      auctionHighlightsHtml: "Online timed auction closing Tuesday evening<br>Classic vehicles consigned from across the UK<br>Bid online from anywhere in the world",
      auctionHouse: "Mathewsons"
    },
    {
      auctionTitle: "The Barons MPC South May 2026 Auction",
      auctionStartDateTime: "30052026:12:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/auction/details/-the-barons-mpc-south-may-2026-auction?au=68",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "manor-park-barons-mpc-south-may-2026",
      auctionFeatured: false,
      auctionHighlights: "73 classic and collector cars at Manor Park South",
      auctionHighlightsHtml: "73 preview lots already published<br>South coast venue at Marchwood, Southampton<br>Live and online bidding",
      auctionHouse: "Manor Park Classics"
    },

    // ---- JUNE 2026 ----
    {
      auctionTitle: "June 2026 Classic & Vintage Car Auction",
      auctionStartDateTime: "04062026:11:00:00",
      auctionWebsite: "https://charterhouse-cars.com/next-car-auction",
      auctionAddress: "Haynes International Motor Museum, Sparkford",
      auctionLat: 51.0408941,
      auctionLng: -2.5602764,
      auctionPhone: "01935 812277",
      auctionCity: "Yeovil",
      auctionPostalCode: "BA22 7LH",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/charterhouse-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Somerset",
      auctionSlug: "charterhouse-june-2026-classic-vintage-car-auction",
      auctionFeatured: false,
      auctionHighlights: "1959 Jaguar XK150 S, 1970 Aston Martin DBS, 1929 Lagonda 2 Litre Tourer",
      auctionHighlightsHtml: "1959 Jaguar XK150 S (est. £10,000–£15,000)<br>1970 Aston Martin DBS<br>1929 Lagonda 2 Litre Tourer<br>2009 Ford Focus RS",
      auctionHouse: "Charterhouse"
    },
    {
      auctionTitle: "Kelham Hall Classic Motors Auction",
      auctionStartDateTime: "17062026:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "Kelham Hall, Main Street, Kelham, Newark, Nottinghamshire",
      auctionLat: 53.0856,
      auctionLng: -0.8493,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Newark",
      auctionPostalCode: "NG23 5QX",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Nottinghamshire",
      auctionSlug: "handh-kelham-hall-june-2026",
      auctionFeatured: true,
      auctionHighlights: "1965 Ferrari 330 GT 2+2 Series I — Estimate £180,000–£220,000",
      auctionHighlightsHtml: "1965 Ferrari 330 GT 2+2 Series I (£180k–£220k)<br>1950 Jaguar XK120 Roadster (£80k–£100k)<br>1973 Jaguar E-Type V12 Roadster (£55k–£65k)",
      auctionHouse: "H&H Classics"
    },
    {
      auctionTitle: "Concours des Légendes — Wilton House",
      auctionStartDateTime: "19062026:11:00:00",
      auctionWebsite: "https://www.drmotoring.com/concours-des-legendes-at-wilton-house",
      auctionAddress: "Wilton House, Wilton, Salisbury, Wiltshire",
      auctionLat: 51.0784,
      auctionLng: -1.8602,
      auctionPhone: "07920 500091",
      auctionCity: "Salisbury",
      auctionPostalCode: "SP2 0BJ",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/dore-and-rees-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Wiltshire",
      auctionSlug: "dore-rees-concours-des-legendes-wilton-2026",
      auctionFeatured: true,
      auctionHighlights: "Fine motor cars, automobilia, watches & jewellery weekend at Wilton House",
      auctionHighlightsHtml: "Three-day weekend at the iconic Wilton House estate<br>Fine Motor Cars sale plus Automobilia and Watches & Jewellery<br>Premium concours setting in the Pembroke family seat",
      auctionHouse: "Dore & Rees"
    },
    {
      auctionTitle: "June 2026 Classic Car Auction (Two-day)",
      auctionStartDateTime: "20062026:10:00:00",
      auctionWebsite: "https://angliacarauctions.co.uk/auctions/2763-20-Jun-2026",
      auctionAddress: "The Cattle Market, Beveridge Way, King's Lynn, Norfolk",
      auctionLat: 52.733709,
      auctionLng: 0.411435,
      auctionPhone: "01553 771881",
      auctionCity: "King's Lynn",
      auctionPostalCode: "PE30 4NB",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/anglia-car-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Norfolk",
      auctionSlug: "anglia-june-2026-classic-car-auction",
      auctionFeatured: true,
      auctionHighlights: "1959 Aston Martin DB4 Series 2 LHD — Estimate £275,000–£325,000",
      auctionHighlightsHtml: "1959 Aston Martin DB4 Series 2 LHD (£275k–£325k)<br>1962 Jaguar E-Type Series I 3.8 FHC (£40k–£45k)<br>Two-day classic vehicle auction<br>Automobilia and registration plates on Sunday",
      auctionHouse: "Anglia Car Auctions"
    },
    {
      auctionTitle: "June 2026 Classic Cars & Motorcycles",
      auctionStartDateTime: "24062026:10:00:00",
      auctionWebsite: "https://www.brightwells.com/timed-sale/5883",
      auctionAddress: "Brightwells Bishops Frome, Worcester Road, Bishops Frome, Herefordshire",
      auctionLat: 52.1730,
      auctionLng: -2.5022,
      auctionPhone: "01568 611122",
      auctionCity: "Bishops Frome",
      auctionPostalCode: "WR6 5AS",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/brightwells-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-june-2026-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Classic Cars, Motorcycles and Modern Classics — entries invited",
      auctionHighlightsHtml: "Timed online auction of classic cars and motorcycles<br>Vehicles physically present at new Bishops Frome site<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "June 2026 Classic Vehicles & Memorabilia Auction",
      auctionStartDateTime: "24062026:10:00:00",
      auctionWebsite: "https://www.mathewsons.co.uk/auction/details/-june-classic-vehicles--memorabilia-auction?au=124",
      auctionAddress: "10 Enterprise Way, Thornton Road, Pickering, North Yorkshire",
      auctionLat: 54.2370631,
      auctionLng: -0.7645434,
      auctionPhone: "01751 474455",
      auctionCity: "Pickering",
      auctionPostalCode: "YO18 7NA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/mathewsons-auction-house-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "North Yorkshire",
      auctionSlug: "mathewsons-june-2026-classic-vehicles-memorabilia",
      auctionFeatured: false,
      auctionHighlights: "Three-day classic vehicle and automobilia memorabilia auction",
      auctionHighlightsHtml: "Three-day classic vehicle auction<br>Wednesday — Friday rolling lot blocks<br>Memorabilia included throughout",
      auctionHouse: "Mathewsons"
    },
    {
      auctionTitle: "The Hampson Auction — June 2026",
      auctionStartDateTime: "28062026:12:00:00",
      auctionWebsite: "https://hampsonauctions.com/auction/details/-the-hampson-auction?au=40",
      auctionAddress: "Winnington Hall, Winnington, Northwich, Cheshire",
      auctionLat: 53.2693,
      auctionLng: -2.5230,
      auctionPhone: "01606 828124",
      auctionCity: "Northwich",
      auctionPostalCode: "CW8 4DU",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "hampson-june-2026-auction",
      auctionFeatured: false,
      auctionHighlights: "Hampson HQ sale at Grade I listed Winnington Hall",
      auctionHighlightsHtml: "Live auction at Hampson HQ — Winnington Hall<br>Classic and collector cars, supercars and motorcycles<br>Buyer's Premium 12.5% + VAT",
      auctionHouse: "Hampson Marketplace"
    },

    // ---- JULY 2026 ----
    {
      auctionTitle: "The Barons MPC South July 2026 Auction",
      auctionStartDateTime: "11072026:12:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "manor-park-barons-mpc-south-july-2026",
      auctionFeatured: false,
      auctionHighlights: "South coast classic car auction at Marchwood",
      auctionHighlightsHtml: "Barons-branded Manor Park sale<br>Live and online bidding available<br>Catalogue building — entries invited",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The MPC North July 2026 Car Auction",
      auctionStartDateTime: "18072026:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "manor-park-mpc-north-july-2026",
      auctionFeatured: false,
      auctionHighlights: "Manor Park North Cheshire HQ classic car sale",
      auctionHighlightsHtml: "Live auction at Ikon House, Runcorn<br>Classic and collector cars from across the UK<br>Catalogue building — entries invited",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Summer Serenade — Windsorview Lakes",
      auctionStartDateTime: "18072026:09:30:00",
      auctionWebsite: "https://www.historics.co.uk/auction/details/a075-the-summer-serenade-windsorview-lakes?au=107",
      auctionAddress: "Windsorview Lakes, Horton Road, Datchet, Berkshire",
      auctionLat: 51.4831,
      auctionLng: -0.5793,
      auctionPhone: "01753 639170",
      auctionCity: "Datchet",
      auctionPostalCode: "SL3 9HX",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/historics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Berkshire",
      auctionSlug: "historics-summer-serenade-windsorview-2026",
      auctionFeatured: true,
      auctionHighlights: "Lakeside classic and collector car auction near Windsor",
      auctionHighlightsHtml: "Stunning lakeside venue near Windsor Castle<br>Historics' premier summer sale<br>Curated selection of classic and modern collector cars",
      auctionHouse: "Historics"
    },
    {
      auctionTitle: "National Motorcycle Museum Sale — Summer 2026",
      auctionStartDateTime: "22072026:10:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction/search?au=566",
      auctionAddress: "National Motorcycle Museum, Coventry Road, Bickenhill, Solihull, West Midlands",
      auctionLat: 52.4419,
      auctionLng: -1.7102,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Solihull",
      auctionPostalCode: "B92 0EJ",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Motorcycle Auctions",
      auctionState: "West Midlands",
      auctionSlug: "handh-national-motorcycle-museum-july-2026",
      auctionFeatured: false,
      auctionHighlights: "Classic motorcycles and vintage scooters at the National Motorcycle Museum",
      auctionHighlightsHtml: "Held at the National Motorcycle Museum, Bickenhill<br>Classic motorcycles, vintage scooters and competition machines<br>Viewing day Tuesday prior",
      auctionHouse: "H&H Classics"
    },
    {
      auctionTitle: "The Iconic Sale at the BRDC Classic 2026 — Competition Cars",
      auctionStartDateTime: "24072026:14:00:00",
      auctionWebsite: "https://www.iconicauctioneers.com/the-iconic-sale-at-the-brdc-classic-2026-competition-cars/2026-07-24/ipp-100",
      auctionAddress: "The Wing, Silverstone Circuit, Towcester, Northamptonshire",
      auctionLat: 52.0786,
      auctionLng: -1.0147,
      auctionPhone: "01926 691141",
      auctionCity: "Silverstone",
      auctionPostalCode: "NN12 8TN",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/auction-house-hero.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Northamptonshire",
      auctionSlug: "iconic-brdc-classic-competition-cars-july-2026",
      auctionFeatured: true,
      auctionHighlights: "Competition cars sale at the BRDC Classic, Silverstone",
      auctionHighlightsHtml: "Dedicated competition cars sale on Friday<br>Held at The Wing, Silverstone Circuit<br>Part of the inaugural BRDC Classic event weekend",
      auctionHouse: "Iconic Auctioneers"
    },
    {
      auctionTitle: "The Iconic Sale at the BRDC Classic 2026 — Collectors' Cars",
      auctionStartDateTime: "25072026:11:00:00",
      auctionWebsite: "https://www.iconicauctioneers.com/the-iconic-sale-at-the-brdc-classic-2026-collectors-cars/2026-07-25/ipp-100",
      auctionAddress: "The Wing, Silverstone Circuit, Towcester, Northamptonshire",
      auctionLat: 52.0786,
      auctionLng: -1.0147,
      auctionPhone: "01926 691141",
      auctionCity: "Silverstone",
      auctionPostalCode: "NN12 8TN",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/auction-house-hero.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Northamptonshire",
      auctionSlug: "iconic-brdc-classic-collectors-cars-july-2026",
      auctionFeatured: true,
      auctionHighlights: "Saturday collectors' cars headline sale at Silverstone",
      auctionHighlightsHtml: "Headline Saturday sale at The Wing<br>Premier classic and collector cars<br>In-person, telephone and online bidding",
      auctionHouse: "Iconic Auctioneers"
    },
    {
      auctionTitle: "Pavilion Gardens Buxton Classic Motors Auction — Summer 2026",
      auctionStartDateTime: "29072026:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "St John's Rd, Buxton, Derbyshire",
      auctionLat: 53.2617,
      auctionLng: -1.9126,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Buxton",
      auctionPostalCode: "SK17 6BE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Derbyshire",
      auctionSlug: "handh-pavilion-gardens-buxton-summer-2026",
      auctionFeatured: false,
      auctionHighlights: "Classic, collector and performance motorcars in Buxton's Pavilion Gardens",
      auctionHighlightsHtml: "Beautiful Pavilion Gardens setting<br>Classic, collector and performance motor cars<br>Wednesday lunchtime sale",
      auctionHouse: "H&H Classics"
    },
    {
      auctionTitle: "July 2026 Classic Vehicles & Memorabilia Auction",
      auctionStartDateTime: "29072026:10:00:00",
      auctionWebsite: "https://www.mathewsons.co.uk/auction/details/-july-classic-vehicles--memorabilia-auction?au=125",
      auctionAddress: "10 Enterprise Way, Thornton Road, Pickering, North Yorkshire",
      auctionLat: 54.2370631,
      auctionLng: -0.7645434,
      auctionPhone: "01751 474455",
      auctionCity: "Pickering",
      auctionPostalCode: "YO18 7NA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/mathewsons-auction-house-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "North Yorkshire",
      auctionSlug: "mathewsons-july-2026-classic-vehicles-memorabilia",
      auctionFeatured: false,
      auctionHighlights: "Three-day classic vehicle and memorabilia auction",
      auctionHighlightsHtml: "Three-day rolling sale Wednesday–Friday<br>Classic vehicles and automobilia memorabilia<br>North Yorkshire's largest classic auction",
      auctionHouse: "Mathewsons"
    },

    // ---- AUGUST 2026 ----
    {
      auctionTitle: "August 2026 Classic Cars & Motorcycles",
      auctionStartDateTime: "05082026:10:00:00",
      auctionWebsite: "https://www.brightwells.com/timed-sale/5884",
      auctionAddress: "Brightwells Bishops Frome, Worcester Road, Bishops Frome, Herefordshire",
      auctionLat: 52.1730,
      auctionLng: -2.5022,
      auctionPhone: "01568 611122",
      auctionCity: "Bishops Frome",
      auctionPostalCode: "WR6 5AS",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/brightwells-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-august-2026-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Mid-summer classic cars, motorcycles and modern classics sale",
      auctionHighlightsHtml: "Timed online auction format<br>Vehicles consigned to Bishops Frome site<br>Online viewing and 12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "The Barons MPC South August 2026 Auction",
      auctionStartDateTime: "22082026:12:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "manor-park-barons-mpc-south-august-2026",
      auctionFeatured: false,
      auctionHighlights: "South coast late summer classic car sale",
      auctionHighlightsHtml: "Manor Park Classics' Barons-branded sale<br>Southampton venue at Marchwood<br>Live and online bidding",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Classic Sale at CarFest 2026",
      auctionStartDateTime: "29082026:11:00:00",
      auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
      auctionAddress: "Laverstoke Park Farm, Overton, Hampshire",
      auctionLat: 51.2531,
      auctionLng: -1.2783,
      auctionPhone: "01926 691141",
      auctionCity: "Overton",
      auctionPostalCode: "RG25 3DR",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/auction-house-hero.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "iconic-classic-sale-carfest-2026",
      auctionFeatured: false,
      auctionHighlights: "Two-day classic sale at the CarFest South festival",
      auctionHighlightsHtml: "Two-day classic and collector sale at CarFest<br>Family festival setting with concours displays<br>Catalogue building — entries invited",
      auctionHouse: "Iconic Auctioneers"
    },
    {
      auctionTitle: "The Gold Cup 2026 — Classic, Performance & Supercar Auction",
      auctionStartDateTime: "31082026:12:00:00",
      auctionWebsite: "https://hampsonauctions.com/auction/details/-the-gold-cup--classic-performance--supercar-auction?au=41",
      auctionAddress: "Oulton Park Circuit, Little Budworth, Tarporley, Cheshire",
      auctionLat: 53.1770869,
      auctionLng: -2.6223099,
      auctionPhone: "01606 828124",
      auctionCity: "Tarporley",
      auctionPostalCode: "CW6 9BW",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "hampson-gold-cup-2026",
      auctionFeatured: true,
      auctionHighlights: "Live auction at the historic Oulton Park Gold Cup weekend",
      auctionHighlightsHtml: "Held at Oulton Park's Gold Cup race weekend<br>Classic, performance and supercar consignments<br>Buyer's Premium 12.5% + VAT (min £250 + VAT)",
      auctionHouse: "Hampson Marketplace"
    },

    // ---- SEPTEMBER 2026 ----
    {
      auctionTitle: "The MPC North September 2026 Car Auction",
      auctionStartDateTime: "05092026:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "manor-park-mpc-north-september-2026",
      auctionFeatured: false,
      auctionHighlights: "Manor Park North early-autumn classic car sale",
      auctionHighlightsHtml: "Live auction at Ikon House, Runcorn<br>Classic and collector cars from across the UK<br>Catalogue building — entries invited",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Autumn Classic Festival at Castle Combe",
      auctionStartDateTime: "12092026:11:00:00",
      auctionWebsite: "https://www.drmotoring.com/the-2026-autumn-classic-festival-at-castle-combe",
      auctionAddress: "Castle Combe Circuit, Castle Combe, Chippenham",
      auctionLat: 51.4937077,
      auctionLng: -2.2169342,
      auctionPhone: "07920 500091",
      auctionCity: "Chippenham",
      auctionPostalCode: "SN14 7EY",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/dore-and-rees-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Wiltshire",
      auctionSlug: "dore-rees-castle-combe-autumn-classic-2026",
      auctionFeatured: false,
      auctionHighlights: "Collectors and competition cars at Castle Combe Autumn Classic",
      auctionHighlightsHtml: "Two-day Autumn Classic festival<br>Held at the historic Castle Combe Circuit<br>Collectors and competition cars",
      auctionHouse: "Dore & Rees"
    },
    {
      auctionTitle: "Pace of Autumn — Ascot Racecourse",
      auctionStartDateTime: "12092026:09:30:00",
      auctionWebsite: "https://www.historics.co.uk/auction/details/a076-pace-of-autumn-ascot-racecourse?au=108",
      auctionAddress: "Ascot Racecourse, High Street, Ascot, Berkshire",
      auctionLat: 51.4128,
      auctionLng: -0.6797,
      auctionPhone: "01753 639170",
      auctionCity: "Ascot",
      auctionPostalCode: "SL5 7JX",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/historics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Berkshire",
      auctionSlug: "historics-pace-of-autumn-ascot-2026",
      auctionFeatured: true,
      auctionHighlights: "Classic and collector cars at Royal Ascot Racecourse",
      auctionHighlightsHtml: "Held at Britain's premier heritage racecourse<br>Curated classic and collector car consignments<br>Historics' flagship autumn sale",
      auctionHouse: "Historics"
    },
    {
      auctionTitle: "September 2026 Classic Cars & Motorcycles",
      auctionStartDateTime: "16092026:10:00:00",
      auctionWebsite: "https://www.brightwells.com/timed-sale/5885",
      auctionAddress: "Brightwells Bishops Frome, Worcester Road, Bishops Frome, Herefordshire",
      auctionLat: 52.1730,
      auctionLng: -2.5022,
      auctionPhone: "01568 611122",
      auctionCity: "Bishops Frome",
      auctionPostalCode: "WR6 5AS",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/brightwells-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-september-2026-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Autumn classic cars, motorcycles and modern classics sale",
      auctionHighlightsHtml: "Timed online auction format<br>Bishops Frome venue with viewing days<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "Kelham Hall Autumn Sale 2026",
      auctionStartDateTime: "23092026:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "Kelham Hall, Main Street, Kelham, Newark, Nottinghamshire",
      auctionLat: 53.0856,
      auctionLng: -0.8493,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Newark",
      auctionPostalCode: "NG23 5QX",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Nottinghamshire",
      auctionSlug: "handh-kelham-hall-autumn-2026",
      auctionFeatured: false,
      auctionHighlights: "H&H's flagship autumn sale at Kelham Hall, Newark",
      auctionHighlightsHtml: "H&H's flagship autumn classic motors sale<br>Held at the historic Kelham Hall<br>Classic, collector and performance motor cars",
      auctionHouse: "H&H Classics"
    },

    // ---- OCTOBER 2026 ----
    {
      auctionTitle: "The Barons MPC South October 2026 Auction",
      auctionStartDateTime: "03102026:12:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "manor-park-barons-mpc-south-october-2026",
      auctionFeatured: false,
      auctionHighlights: "Autumn south coast classic car sale",
      auctionHighlightsHtml: "Manor Park Classics' South October sale<br>Marchwood venue near Southampton<br>Live and online bidding",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Hampson Auction — October 2026",
      auctionStartDateTime: "11102026:12:00:00",
      auctionWebsite: "https://hampsonauctions.com/auction/details/-the-hampson-auction?au=48",
      auctionAddress: "Winnington Hall, Winnington, Northwich, Cheshire",
      auctionLat: 53.2693,
      auctionLng: -2.5230,
      auctionPhone: "01606 828124",
      auctionCity: "Northwich",
      auctionPostalCode: "CW8 4DU",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "hampson-october-2026-auction",
      auctionFeatured: false,
      auctionHighlights: "Hampson HQ autumn sale at Winnington Hall",
      auctionHighlightsHtml: "Live auction at Winnington Hall<br>Classic and collector cars, supercars and motorcycles<br>Buyer's Premium 12.5% + VAT",
      auctionHouse: "Hampson Marketplace"
    },
    {
      auctionTitle: "Pavilion Gardens Buxton Classic Motors Auction — Autumn 2026",
      auctionStartDateTime: "14102026:12:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "St John's Rd, Buxton, Derbyshire",
      auctionLat: 53.2617,
      auctionLng: -1.9126,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Buxton",
      auctionPostalCode: "SK17 6BE",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Derbyshire",
      auctionSlug: "handh-pavilion-gardens-buxton-autumn-2026",
      auctionFeatured: false,
      auctionHighlights: "Autumn classic, collector and performance motorcars at Buxton",
      auctionHighlightsHtml: "Beautiful Pavilion Gardens setting<br>Classic, collector and performance motor cars<br>Wednesday lunchtime sale",
      auctionHouse: "H&H Classics"
    },
    {
      auctionTitle: "The MPC North October 2026 Car Auction",
      auctionStartDateTime: "17102026:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "manor-park-mpc-north-october-2026",
      auctionFeatured: false,
      auctionHighlights: "Manor Park North autumn classic car sale",
      auctionHighlightsHtml: "Live auction at Ikon House, Runcorn<br>Classic and collector cars from across the UK<br>Catalogue building — entries invited",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "October 2026 Classic Cars & Motorcycles",
      auctionStartDateTime: "28102026:10:00:00",
      auctionWebsite: "https://www.brightwells.com/timed-sale/5886",
      auctionAddress: "Brightwells Bishops Frome, Worcester Road, Bishops Frome, Herefordshire",
      auctionLat: 52.1730,
      auctionLng: -2.5022,
      auctionPhone: "01568 611122",
      auctionCity: "Bishops Frome",
      auctionPostalCode: "WR6 5AS",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/brightwells-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-october-2026-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Late autumn classic cars, motorcycles and modern classics sale",
      auctionHighlightsHtml: "Timed online auction format<br>Bishops Frome venue with viewing days<br>12% buyer's premium + VAT",
      auctionHouse: "Brightwells"
    },
    {
      auctionTitle: "National Motorcycle Museum Sale — Autumn 2026",
      auctionStartDateTime: "28102026:10:00:00",
      auctionWebsite: "https://www.handh.co.uk/auction-calendar/",
      auctionAddress: "National Motorcycle Museum, Coventry Road, Bickenhill, Solihull, West Midlands",
      auctionLat: 52.4419,
      auctionLng: -1.7102,
      auctionPhone: "+44 (0) 1925 210035",
      auctionCity: "Solihull",
      auctionPostalCode: "B92 0EJ",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/h-and-h-classics-logo.avif",
      auctionCategory: "Classic Motorcycle Auctions",
      auctionState: "West Midlands",
      auctionSlug: "handh-national-motorcycle-museum-october-2026",
      auctionFeatured: false,
      auctionHighlights: "Classic motorcycles at the National Motorcycle Museum",
      auctionHighlightsHtml: "Held at the National Motorcycle Museum, Bickenhill<br>Classic motorcycles, vintage scooters and competition machines<br>Viewing day Tuesday prior",
      auctionHouse: "H&H Classics"
    },

    // ---- NOVEMBER 2026 ----
    {
      auctionTitle: "The MPC North November 2026 Platinum Auction",
      auctionStartDateTime: "11112026:18:30:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "manor-park-mpc-north-platinum-november-2026",
      auctionFeatured: true,
      auctionHighlights: "Manor Park's premium Platinum evening sale",
      auctionHighlightsHtml: "Manor Park Classics' Platinum-tier evening sale<br>Curated selection of premium classics and supercars<br>Live and online bidding",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Iconic Sale at the NEC Classic Motor Show 2026",
      auctionStartDateTime: "14112026:11:00:00",
      auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
      auctionAddress: "NEC, North Avenue, Marston Green, Birmingham",
      auctionLat: 52.4510,
      auctionLng: -1.7235,
      auctionPhone: "01926 691141",
      auctionCity: "Birmingham",
      auctionPostalCode: "B40 1NT",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/auction-house-hero.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "West Midlands",
      auctionSlug: "iconic-nec-classic-motor-show-2026-day1",
      auctionFeatured: true,
      auctionHighlights: "Day 1 of Iconic's biggest annual classic car auction at the NEC",
      auctionHighlightsHtml: "Headline sale of the year at the NEC Classic Motor Show<br>Two-day live auction with international bidding<br>Wide range of prestigious classic and collector vehicles",
      auctionHouse: "Iconic Auctioneers"
    },
    {
      auctionTitle: "The Classic Sale at the NEC Classic Motor Show 2026 — Day 2",
      auctionStartDateTime: "15112026:11:00:00",
      auctionWebsite: "https://www.iconicauctioneers.com/auction/upcoming-auctions-cars",
      auctionAddress: "NEC, North Avenue, Marston Green, Birmingham",
      auctionLat: 52.4510,
      auctionLng: -1.7235,
      auctionPhone: "01926 691141",
      auctionCity: "Birmingham",
      auctionPostalCode: "B40 1NT",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/auction-house-hero.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "West Midlands",
      auctionSlug: "iconic-nec-classic-motor-show-2026-day2",
      auctionFeatured: true,
      auctionHighlights: "Day 2 of the NEC Classic Motor Show Sale",
      auctionHighlightsHtml: "Second day of the premier NEC Classic Motor Show auction<br>Additional classic cars and automobilia<br>Access with auction catalogue",
      auctionHouse: "Iconic Auctioneers"
    },
    {
      auctionTitle: "The Barons MPC South November 2026 Auction",
      auctionStartDateTime: "14112026:12:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Unit 6 Harbour Close, Cracknore Industrial Park, Marchwood, Southampton",
      auctionLat: 50.8907989,
      auctionLng: -1.4710819,
      auctionPhone: "02380 668413",
      auctionCity: "Southampton",
      auctionPostalCode: "SO40 4AF",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Hampshire",
      auctionSlug: "manor-park-barons-mpc-south-november-2026",
      auctionFeatured: false,
      auctionHighlights: "South coast pre-winter classic car sale",
      auctionHighlightsHtml: "Manor Park Classics' Barons-branded sale<br>Southampton venue at Marchwood<br>Live and online bidding",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "The Hampson Auction — November 2026",
      auctionStartDateTime: "22112026:12:00:00",
      auctionWebsite: "https://hampsonauctions.com/auction/details/-the-hampson-auction?au=43",
      auctionAddress: "Winnington Hall, Winnington, Northwich, Cheshire",
      auctionLat: 53.2693,
      auctionLng: -2.5230,
      auctionPhone: "01606 828124",
      auctionCity: "Northwich",
      auctionPostalCode: "CW8 4DU",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/hampson-marketplace-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "hampson-november-2026-auction",
      auctionFeatured: false,
      auctionHighlights: "Hampson HQ pre-winter sale at Winnington Hall",
      auctionHighlightsHtml: "Live auction at Winnington Hall<br>Classic and collector cars, supercars and motorcycles<br>Buyer's Premium 12.5% + VAT",
      auctionHouse: "Hampson Marketplace"
    },
    {
      auctionTitle: "The Brooklands Velocity — Mercedes-Benz World",
      auctionStartDateTime: "28112026:09:30:00",
      auctionWebsite: "https://www.historics.co.uk/auction/details/a077-the-brooklands-velocity-mercedes-benz-world?au=109",
      auctionAddress: "Mercedes-Benz World, Brooklands Drive, Weybridge, Surrey",
      auctionLat: 51.3477,
      auctionLng: -0.4683,
      auctionPhone: "01753 639170",
      auctionCity: "Weybridge",
      auctionPostalCode: "KT13 0SL",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/historics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Surrey",
      auctionSlug: "historics-brooklands-velocity-mercedes-benz-world-2026",
      auctionFeatured: true,
      auctionHighlights: "Classic and collector cars at Mercedes-Benz World, Brooklands",
      auctionHighlightsHtml: "Historics' final live sale of the year<br>Held at Mercedes-Benz World on the historic Brooklands site<br>Mercedes-Benz heritage and wider collector consignments",
      auctionHouse: "Historics"
    },

    // ---- DECEMBER 2026 ----
    {
      auctionTitle: "The MPC North December 2026 Car Auction",
      auctionStartDateTime: "05122026:11:00:00",
      auctionWebsite: "https://www.manorparkclassics.com/upcoming-auctions/",
      auctionAddress: "Ikon House, Tudor Road, Runcorn, Cheshire",
      auctionLat: 53.3447861,
      auctionLng: -2.6787376,
      auctionPhone: "01925 210035",
      auctionCity: "Runcorn",
      auctionPostalCode: "WA7 1TA",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/manor-park-classics-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Cheshire",
      auctionSlug: "manor-park-mpc-north-december-2026",
      auctionFeatured: false,
      auctionHighlights: "Manor Park North end-of-year Christmas auction",
      auctionHighlightsHtml: "Final North sale of the year at Ikon House<br>Classic and collector cars from across the UK<br>Catalogue building — entries invited",
      auctionHouse: "Manor Park Classics"
    },
    {
      auctionTitle: "December 2026 Classic Cars & Motorcycles",
      auctionStartDateTime: "09122026:10:00:00",
      auctionWebsite: "https://www.brightwells.com/timed-sale/5887",
      auctionAddress: "Brightwells Bishops Frome, Worcester Road, Bishops Frome, Herefordshire",
      auctionLat: 52.1730,
      auctionLng: -2.5022,
      auctionPhone: "01568 611122",
      auctionCity: "Bishops Frome",
      auctionPostalCode: "WR6 5AS",
      auctionCountryCode: "GB",
      auctionImageUrl: "/assets/images/auction-houses/brightwells-auctions-logo.avif",
      auctionCategory: "Classic Car Auctions",
      auctionState: "Herefordshire",
      auctionSlug: "brightwells-december-2026-classic-cars-motorcycles",
      auctionFeatured: false,
      auctionHighlights: "Brightwells' final sale of 2026 — classic cars and motorcycles",
      auctionHighlightsHtml: "Brightwells' final sale of the year<br>Timed online auction format<br>Christmas timing — perfect for last-minute consignments",
      auctionHouse: "Brightwells"
    },
  ];

  // Sort auctions by date
  auctions.sort((a, b) => {
    const dateA = parseAuctionDate(a.auctionStartDateTime);
    const dateB = parseAuctionDate(b.auctionStartDateTime);

    // Handle cases where dates might be null or invalid
    if (!dateA && !dateB) return 0; // both are invalid/null, consider them equal
    if (!dateA) return 1; // null/invalid dateA comes after valid dateB
    if (!dateB) return -1; // null/invalid dateB comes after valid dateA

    return dateA - dateB; // Ascending order
  });

  // Return only upcoming auctions (filtered and sorted)
  return filterUpcomingAuctions(auctions);
};