module.exports = function() {
  return [
    {
      title: "Rolls-Royce Enthusiasts' Club",
      website: "https://rrec.org.uk/",
      address: "The Hunt House, Paulerspury, Northants, NN12 7NA",
      phone: "+44(1327)811788",
      email: "hello@rrec.org.uk",
      city: "Paulerspury",
      postalCode: "NN12 7NA",
      countryCode: "GB",
      imageUrl: "/assets/images/rolls-royce-enthusiasts.jpg",
      category: "Car Club",
      state: "Northamptonshire",
      slug: "rolls-royce-enthusiasts-club",
      featured: true,
      description: "The Rolls-Royce Enthusiasts' Club is a vibrant community of enthusiasts dedicated to the preservation and celebration of Rolls-Royce and Bentley motor cars. With members worldwide, the club offers a wealth of knowledge, events, and resources for owners and enthusiasts alike."
    },
    {
      title: "Rolls-Royce Enthusiasts' Wessex Section",
      website: "https://rrecwessex.org.uk/",
      address: "",
      phone: "079765 70036",
      email: "secretary@rrecwessex.org.uk",
      city: "",
      postalCode: "",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "Wessex",
      slug: "rolls-royce-enthusiasts-club-wessex",
      description: "The Wessex Section of the Rolls-Royce Enthusiasts' Club caters to members in the Wessex region, organizing local events and gatherings for Rolls-Royce and Bentley enthusiasts."
    },
    {
      title: "Rover P4 Drivers' Guild",
      website: "https://www.roverp4dg.org.uk",
      address: "Paddock Bend, 60 Stratford Road, Cosgrove, Northants, MK19 7BD.",
      phone: "",
      email: "",
      city: "Northants",
      postalCode: "MK19 7BD",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "",
      slug: "rover-p4-drivers-guild",
      description: "The Rover P4 Drivers' Guild is dedicated to the preservation and enjoyment of Rover P4 vehicles, affectionately known as 'Aunties'. The club provides technical support, spares, and regular events for P4 enthusiasts."
    },
    {
      title: "Rover SDI Club",
      website: "https://www.roversd1club.net",
      address: "The Rover SDI Club, PO Box 2841, Hawksworth, Swindon, SN2 1WS.",
      phone: "0845 306230",
      email: "",
      city: "Swindon",
      postalCode: "SN2 1WS",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "",
      slug: "rover-sdi-club",
      description: "The Rover SDI Club is focused on the Rover SD1 model produced between 1976 and 1986. The club offers technical support, parts sourcing assistance, and regular meetings for SD1 owners and enthusiasts."
    },
    {
      title: "Rolls-Royce Enthusiasts' Club - Surrey Section",
      website: "https://www.rrec-surrey.uk/",
      address: "Melrose Cottage, Cranleigh Road, Ewhurst, Surrey GU6 7RJ",
      phone: "01483 271853",
      email: "secretary@rrec-surrey.uk",
      city: "Surrey",
      postalCode: "GU6 7RJ",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "Surrey",
      slug: "rolls-royce-enthusiasts-club-surrey-section",
      description: "The Surrey Section of the Rolls-Royce Enthusiasts' Club serves members in the Surrey area, organizing events, drives, and social gatherings for local Rolls-Royce and Bentley enthusiasts."
    },
    {
      title: "Rover P6 Owners Club",
      website: "https://www.p6roc.com",
      address: "Wood Nook Farm, 2 Huddersfield Road, Shelley, Huddersfield, HD8 8HJ",
      phone: "01484 607772",
      email: "",
      city: "Huddersfield",
      postalCode: "HD8 8HJ",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "",
      slug: "rover-p6-owners-club",
      description: "The Rover P6 Owners Club is dedicated to the preservation and enjoyment of the Rover P6 model, produced between 1963 and 1977. The club provides technical support, spare parts, and regular events for P6 enthusiasts."
    },
    {
      title: "Rover P5 Owners Club",
      website: "https://www.roverp5club.org.uk",
      address: "Membership Secretary Rover P5 Club, 13 Glen Avenue, Ashford, Middlesex TW15 2JE, United Kingdom.",
      phone: "01784 258166",
      email: "",
      city: "Ashford",
      postalCode: "TW15 2JE",
      countryCode: "GB",
      imageUrl: "",
      category: "Car Club",
      state: "Middlesex",
      slug: "rover-p5-owners-club",
      description: "The Rover P5 Owners Club supports enthusiasts of the Rover P5 and P5B models. The club organizes events, provides technical advice, and helps members source spares for these classic British luxury cars."
    },
    {
      title: "Club Peugeot UK",
      website: "https://www.clubpeugeotuk.org",
      address: "85 Warwick Road, Banbury, Oxfordshire, OX16 9HJ",
      phone: "01295 272587",
      email: "info@clubpeugeotuk.org",
      city: "Banbury",
      postalCode: "OX16 9HJ",
      countryCode: "GB",
      imageUrl: "/assets/images/club-peugeot-uk.jpg",
      category: "Car Club",
      state: "Oxfordshire",
      slug: "club-peugeot-uk",
      featured: true,
      description: "Club Peugeot UK is the official club for all Peugeot enthusiasts in the United Kingdom. Catering to owners of both classic and modern Peugeots, the club organizes rallies, shows, and technical workshops throughout the year."
    },
    {
      title: "Ford Classic and Capri Owners Club",
      website: "https://www.fordcapriclub.co.uk",
      address: "72 Manor Road, Burnham-on-Sea, Somerset, TA8 2AS",
      phone: "07789 123456",
      email: "secretary@fordcapriclub.co.uk",
      city: "Burnham-on-Sea",
      postalCode: "TA8 2AS",
      countryCode: "GB",
      imageUrl: "/assets/images/ford-classic-capri.jpg",
      category: "Car Club",
      state: "Somerset",
      slug: "ford-classic-and-capri-owners-club",
      featured: true,
      description: "The Ford Classic and Capri Owners Club is dedicated to the preservation and enjoyment of Ford Consul Classics, Capris, and related vehicles. The club offers technical support, spares, and regular events across the UK."
    },
    {
      title: "North West Casual Classics",
      website: "https://www.northwestcasualclassics.com",
      address: "156 Chester Road, Warrington, Cheshire, WA4 6AG",
      phone: "01925 234567",
      email: "info@northwestcasualclassics.com",
      city: "Warrington",
      postalCode: "WA4 6AG",
      countryCode: "GB",
      imageUrl: "/assets/images/nw-casual-classics.jpg",
      category: "Car Club",
      state: "Cheshire",
      slug: "north-west-casual-classics",
      featured: true,
      description: "North West Casual Classics is a friendly club for enthusiasts of all classic vehicles in the North West of England. With a relaxed approach to classic car ownership, the club welcomes vehicles of all makes, models, and conditions."
    },
    {
      title: "Range Rover Register",
      website: "https://www.rangeroverregister.org",
      address: "PO Box 123, Reading, Berkshire, RG1 5AB",
      phone: "0118 9876543",
      email: "membership@rangeroverregister.org",
      city: "Reading",
      postalCode: "RG1 5AB",
      countryCode: "GB",
      imageUrl: "/assets/images/range-rover-register.jpg",
      category: "Car Club",
      state: "Berkshire",
      slug: "range-rover-register",
      featured: true,
      description: "The Range Rover Register is the premier club for Range Rover enthusiasts, covering all generations from the classic three-door to the latest models. The club offers technical advice, parts sources, and regular off-road events."
    },
    {
      title: "Jaguar E-Type Club",
      website: "https://www.e-typeclub.com",
      address: "Trent Park, Cockayne Hatley, Bedfordshire, SG19 2EA",
      phone: "01234 567890",
      email: "enquiries@e-typeclub.com",
      city: "Bedfordshire",
      postalCode: "SG19 2EA",
      countryCode: "GB",
      imageUrl: "/assets/images/jaguar-e-type-club.jpg",
      category: "Car Club",
      state: "Bedfordshire",
      slug: "jaguar-e-type-club",
      description: "The Jaguar E-Type Club is exclusively for owners and enthusiasts of the iconic Jaguar E-Type. The club offers technical support, tours, rallies, and track days for members to enjoy their E-Types to the fullest."
    }
  ];
};
