module.exports = function () {
  // This would typically be fetched from a headless CMS
  // For now, using static data based on the provided sample
  return [
    {
      eventTitle: "Netherby Hall Annual Car Show 2025",
      eventStartDateTime: "02082025:10:00:00",
      eventEndDateTime: "03082025:16:00:00",
      eventTicketPrice: "Adult £12.00 single day - £20.00 weekend - Group (up to 6) £45.00 single day - £70.00 weekend - Children under 16 free - Exhibitor & 1 guest £5.00",
      eventWebsite: "https://netherbyhall.co.uk/event/netherby-hall-2025-car-show-in-cumbria",
      eventAddress: "Netherby Hall, Netherby, Longtown, Carlisle, Cumbria, CA6 5PR, UK",
      eventLat: 55.035662,
      eventLng: -2.9482453,
      eventPhone: "01228 792732",
      eventEmail: "events@netherbyhall.co.uk",
      eventCity: "Longtown",
      eventPostalCode: "CA6 5PR",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/netherby-hall-car-show-2025.avif",
      eventCategory: ["Classic Cars", "Performance Cars", "Supercars", "Vintage Vehicles", "Historic Estate", "Family Event"],
      eventState: "Cumbria",
      eventSlug: "netherby-hall-annual-car-show-2025",
      eventFeatured: true,
      eventDescription: "Set in the beautiful Cumbrian countryside at historic Netherby Hall. Saturday features Performance and Super Cars, Sunday showcases Classic and Vintage vehicles (pre-2005 registration). Rare and unique classic cars with detailed vehicle histories. Includes food and drink stalls, craft stalls, stunning estate grounds, and luxury accommodation available on-site."
    },
    {
      eventTitle: "South Yorkshire Classic Car & Motorcycle Show 2025",
      eventStartDateTime: "03082025:10:00:00",
      eventEndDateTime: "03082025:16:00:00",
      eventTicketPrice: "Adult £10.50 advance (£12.50 gate) - Child (5-14) £3.50 - Exhibitor £5.50 advance (£7.50 from April)",
      eventWebsite: "https://classicshows.org/events/south-yorkshire-classic-car-motorcycle-show-3-august-2025",
      eventAddress: "Wentworth Woodhouse, Wentworth, Rotherham, South Yorkshire, S62 7TQ, UK",
      eventLat: 53.47417,
      eventLng: -1.40472,
      eventPhone: "01484 667776",
      eventEmail: "info@classicshows.org",
      eventCity: "Rotherham",
      eventPostalCode: "S62 7TQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/south-yorkshire-classic-car-motorcycle-show.avif",
      eventCategory: ["Classic Cars", "Motorcycles", "Autojumble", "Trade Stands", "Historic House"],
      eventState: "South Yorkshire",
      eventSlug: "south-yorkshire-classic-car-motorcycle-show-2025",
      eventFeatured: true,
      eventDescription: "Spectacular classic car and motorcycle show at the magnificent Wentworth Woodhouse, often listed as the largest private residence in the UK. Features wide range of classic vehicles, autojumble stalls, street food, drinks stands, and access to the stunning historic estate grounds and gardens."
    },
    {
      eventTitle: "2025 BVAC Classic",
      eventStartDateTime: "08062025:11:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "£15.00",
      eventWebsite: "https://bvac.org.uk/event/2025-bvac-classic/",
      eventAddress: "Thirlestane Castle, Lauder, Scottish Borders, TD2 6RU, UK",
      eventLat: 55.722255,
      eventLng: -2.743447,
      eventPhone: "01896 849597",
      eventEmail: "info@bvac.org.uk",
      eventCity: "Lauder",
      eventPostalCode: "TD2 6RU",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/bvac-classic-2025.avif",
      eventCategory: ["Car Show", "Classic Cars", "Family Event"],
      eventState: "Scottish Borders",
      eventSlug: "bvac-classic-2025",
      eventFeatured: true,
      eventDescription: "The 2025 BVAC Classic, celebrating its 50th anniversary, is Scotland's premier classic car show. Held at the picturesque Thirlestane Castle, the event showcases over 1,000 classic and vintage cars, live motorsport action, stunt displays, a retail village, and a variety of food and drink options, making it a perfect day out for the whole family."
    },
    {
      eventTitle: "Gloucestershire Vintage & Country Extravaganza 2025",
      eventStartDateTime: "01082025:10:00:00",
      eventEndDateTime: "03082025:17:00:00",
      eventTicketPrice: "Adult £13.50 advance (£15 gate) - Child (5-15) £4.50 advance (£5 gate) - Children under 5 free - Family ticket (2 adults, 2 children) £31.50 advance (£35 gate)",
      eventWebsite: "https://www.glosvintageextravaganza.co.uk",
      eventAddress: "South Cerney Airfield, Northmoor Lane, South Cerney, Cirencester, Gloucestershire, GL7 5QD, UK",
      eventLat: 51.6885855,
      eventLng: -1.923215,
      eventPhone: "01453 890891",
      eventEmail: "enquiries.svtec@hotmail.com",
      eventCity: "Cirencester",
      eventPostalCode: "GL7 5QD",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/glosvintageimage2025.avif",
      eventCategory: ["Steam Rally", "Vintage Transport", "Classic Cars", "Motorcycles", "Family Event", "Country Show", "50th Anniversary"],
      eventState: "Gloucestershire",
      eventSlug: "gloucestershire-vintage-country-extravaganza-2025",
      eventFeatured: true,
      eventDescription: "The 50th anniversary of the Gloucestershire Vintage & Country Extravaganza returns to South Cerney Airfield. Regarded as one of the biggest and best steam, vintage and countryside events in the UK with nearly 1000 classic cars, hundreds of motorbikes, steam engines, vintage buses, military vehicles, and much more. Features three live arenas, vintage entertainment tent with live music and dance, animal and countryside arena, vintage fairground, trade stands, craft marquee, and free vintage bus rides."
    },
    {
      eventTitle: "Folkestone and Ashford Military Show 2025",
      eventStartDateTime: "07062025:10:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "Adult £8.00 - Child £5.00 - Family £25.00",
      eventWebsite: "http://www.faams.co.uk",
      eventAddress: "Sellindge Show Ground, M20 Junction 11, Between Folkestone and Ashford, Kent, TN25 6H, UK",
      eventLat: 51.1106317,
      eventLng: 1.0258078,
      eventPhone: "07759 283833",
      eventEmail: "Info@faams.co.uk",
      eventCity: "Sellindge",
      eventPostalCode: "TN25 6H",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/folkestone-ashford-military-show-2025.avif",
      eventCategory: ["Military Show","Classic Cars","Family Event","Charity Event"],
      eventState: "Kent",
      eventSlug: "folkestone-ashford-military-show-2025",
      eventFeatured: true,
      eventDescription: "The Folkestone and Ashford Military Show is a two-day event organized by a cadet group for charity to help the Royal British Legion raise funds. Features entertainment in the marquee, arena displays, youth motorcycle display team, static displays, stalls, classic cars and motorcycles, food stalls, full funfair, and camping facilities."
    },
    {
      eventTitle: "Loch Ness Classic and Vintage Car Tour 2025",
      eventStartDateTime: "07062025:10:30:00",
      eventEndDateTime: "07062025:16:30:00",
      eventTicketPrice: "Free (Charity Donations)",
      eventWebsite: "https://lochnessclassiccartour.weebly.com",
      eventAddress: "Inverness Ice Centre, Inverness, Scotland, IV1 1RY, UK",
      eventLat: 57.4635294,
      eventLng: -4.2397648,
      eventPhone: "07774 695640",
      eventEmail: "nicol.manson@btinternet.com",
      eventCity: "Inverness",
      eventPostalCode: "IV1 1RY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/loch-ness-classic-tour-2025.avif",
      eventCategory: ["Car Tour","Classic Cars","Charity Event","Scenic Tour"],
      eventState: "Scotland",
      eventSlug: "loch-ness-classic-car-tour-2025",
      eventFeatured: true,
      eventDescription: "The Loch Ness Classic and Vintage Car Tour is a non-competitive touring event for classic, vintage, and sporting vehicles. The 160-mile route covers stunning Highland landscapes including Loch Ness, Black Isle, Easter Ross, and Sutherland. Start and finish at Inverness Ice Centre. No entry fee but entrants are encouraged to raise charity sponsorship. Public viewing available at start (10:30am) and finish (3:30pm onwards)."
    },
    {
      eventTitle: "Masters of Motoring - Classic & Sports Car Show 2025",
      eventStartDateTime: "08062025:10:00:00",
      eventEndDateTime: "08062025:16:30:00",
      eventTicketPrice: "£25.00 - £55.00",
      eventWebsite: "https://bowood.org/event/masters-of-motoring-classic-sports-car-show/",
      eventAddress: "Bowood House & Gardens, Derry Hill, Chippenham, Wiltshire, SN11 9PQ, UK",
      eventLat: 51.4290567,
      eventLng: -2.0380402,
      eventPhone: "01249 812102",
      eventEmail: "events@bowood.org",
      eventCity: "Chippenham",
      eventPostalCode: "SN11 9PQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/bowood-masters-of-motoring-classic-sports-car-show-2025.avif",
      eventCategory: ["Classic Cars","Supercars","Luxury Cars","Concours"],
      eventState: "Wiltshire",
      eventSlug: "masters-of-motoring-classic-sports-car-show-2025",
      eventFeatured: true,
      eventDescription: "Experience luxury motoring at its finest as Masters of Motoring showcases a breathtaking assembly of concours supercars, heritage classics, and modern sports cars in the prestigious setting of Bowood House. Join a community of automotive aficionados to appreciate these stunning examples that celebrate the artistry of automotive design across generations."
    },
    {
      eventTitle: "Stoke Row Steam Rally 2025",
      eventStartDateTime: "07062025:09:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "£12.00",
      eventWebsite: "https://stokerowsteamrally.com/",
      eventAddress: "Hill Bottom, Whitchurch Hill, Reading, Berkshire, RG8 7RL, UK",
      eventLat: 51.527131,
      eventLng: -1.072597,
      eventPhone: "01491 680242",
      eventEmail: "StokeRowSR@gmail.com",
      eventCity: "Reading",
      eventPostalCode: "RG8 7RL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/stoke-row-steam-rally-2025.avif",
      eventCategory: ["Steam Rally","Classic Cars","Historic Vehicles"],
      eventState: "Berkshire",
      eventSlug: "stoke-row-steam-rally-2025",
      eventFeatured: false,
      eventDescription: "Annual Stoke Row Steam Rally featuring more than 70 steam vehicles of historic importance, plus classic cars. A celebration of steam power and vintage machinery in the Berkshire countryside."
     },
     {
      eventTitle: "VSCC Harewood Hill - Climb Speed Championship Round 3 2025",
      eventStartDateTime: "08062025:09:00:00",
      eventEndDateTime: "08062025:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.vscc.co.uk/page/events?eventID=1917",
      eventAddress: "Harewood Ave, Harewood, Leeds LS17 9LA, Yorkshire",
      eventLat: 53.9051086,
      eventLng: -1.4928095,
      eventPhone: "01234 567890",
      eventEmail: "events@vscc.co.uk",
      eventCity: "Leeds",
      eventPostalCode: "TBC",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/vscc-speed-championship-2025.avif",
      eventCategory: ["Speed Championship","Hill Climb","Competition","Classic Cars"],
      eventState: "Yorkshire",
      eventSlug: "vscc-speed-championship-round-3-2025",
      eventFeatured: true,
      eventDescription: "Round 3 of the VSCC Speed Championship, hosted by friends at BARC. Set near the delightful Yorkshire dales, the whole hill is visible from the paddock, making it a popular venue for both public and competitors. A classic speed event in a stunning location."
     },
     {
      eventTitle: "Cleveleys Car Show 2025",
      eventStartDateTime: "08062025:09:00:00",
      eventEndDateTime: "08062025:16:00:00",
      eventTicketPrice: "Free",
      eventWebsite: "https://www.facebook.com/events/640080858576148/",
      eventAddress: "Town Centre and Promenade, Cleveleys, Lancashire, FY5 1PJ, UK",
      eventLat: 53.8759119,
      eventLng: -3.0337209,
      eventPhone: "",
      eventEmail: "ukwheelsevents@gmail.com",
      eventCity: "Cleveleys",
      eventPostalCode: "FY5 1PJ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/cleveleys-car-show-2025.avif",
      eventCategory: ["Classic Vehicles","Town Centre Event","Free Event"],
      eventState: "Lancashire",
      eventSlug: "cleveleys-classic-vehicle-show-2025",
      eventFeatured: true,
      eventDescription: "The Cleveleys Classic Vehicle Show turns the seaside promenade and town centre into a spectacular automotive celebration! Hundreds of stunning classic cars, bikes, and vehicles of all shapes and sizes line the seafront and fill the streets, creating an incredible display just outside Blackpool. With all the action happening right by the coast, you can enjoy brilliant shops, cafes, and restaurants while soaking up that classic seaside atmosphere - the perfect blend of motoring heritage and seaside charm!"
     },
    {
      eventTitle: "Brooklands Best of British Day 2025",
      eventStartDateTime: "26052025:10:00:00",
      eventEndDateTime: "26052025:17:00:00",
      eventTicketPrice: "£26.40",
      eventWebsite: "https://www.brooklandsmuseum.com/whats-on/best-of-british-2025",
      eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey, KT13 0SL, UK",
      eventLat: 51.354512,
      eventLng: -0.4669199,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/best-of-british-2025.avif",
      eventCategory: ["Car Show", "Motorcycle Show", "British Vehicles"],
      eventState: "Surrey",
      eventSlug: "best-of-british-2025",
      eventFeatured: false,
      eventDescription: "Enjoy a day of British vehicles with lots of family entertainment, plus Test Hill ascents! Meet Paddington™ at intervals throughout the day. There will be a huge display of British built vehicles, from the pre-war Alvis, Norton and Sunbeam right through to the latest Jaguar models. All British marques are welcome to join, independently or with a Car Club. Admission includes access to Brooklands Museum for the day. Normal Museum Admission applies. Children under 4 go free. Members go free. Gates open at 9am for classic vehicles via Campbell Gate off Brooklands Road."
   },
   {
    eventTitle: "Mopar Muscle 2025",
    eventStartDateTime: "25052025:10:00:00",
    eventEndDateTime: "25052025:17:00:00",
    eventTicketPrice: "£26.40",
    eventWebsite: "https://www.brooklandsmuseum.com/whats-on/mopar-muscle-day",
    eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey",
    eventLat: 51.354711,
    eventLng: -0.464371,
    eventPhone: "01932 857381",
    eventEmail: "info@brooklandsmuseum.com",
    eventCity: "Weybridge",
    eventPostalCode: "KT13 0SL",
    eventCountryCode: "GB",
    eventImageUrl: "/assets/images/events/mopar-muscle-2025.avif",
    eventCategory: ["Car Show", "Classic Cars", "American Cars", "Family Event"],
    eventState: "Surrey",
    eventSlug: "mopar-muscle-2025",
    eventFeatured: true,
    eventDescription: "Enjoy a display of MOPAR Muscle cars on the Finishing Straight and Banking. Expect a feast of chrome and colour with Chryslers, Dodges, Plymouths and other MOPAR Muscle cars, many beautifully restored with engines up to 9,000ccs. The event includes food stalls, trade stands, live music and access to all Brooklands Museum exhibits for the day."
    },
    {
      eventTitle: "Brooklands Drive It Day 2025",
      eventStartDateTime: "27052025:10:00:00",
      eventEndDateTime: "27052025:17:00:00",
      eventTicketPrice: "£26.40",
      eventWebsite: "https://brooklandsmuseum.seetickets.com/event/event-day-drive-it-day/brooklands-museum/3230083",
      eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey, KT13 0SL, UK",
      eventLat: 51.354512,
      eventLng: -0.4669199,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/brookands-drive-it-day-2025.avif",
      eventCategory: ["Car Show", "Motorcycle Show", "Drive It Day"],
      eventState: "Surrey",
      eventSlug: "drive-it-day-2025",
      eventFeatured: true,
      eventDescription: "Join this year's Drive It Day along with Ride It Day for the Motorcycle Community. Bring your classic car or motorcycle to take part in this year's Drive It Day, in aid of the NSPCC's Childline®, to raise money to support vulnerable children. Pre-31 July 1995 vehicles are welcome. Gates open at 9am for classic vehicles via Campbell Gate off Brooklands Road. The Museum and Sunbeam Café open at 10am. Child Entry (4-17 Yrs) (W/ DONATION)	£11.00"
    },
    {
      eventTitle: "Classic Car Show 2025",
      eventStartDateTime: "08062025:10:00:00",
      eventEndDateTime: "08062025:16:00:00",
      eventTicketPrice: "£10.00",
      eventWebsite:
        "https://piedpiperappeal.co.uk/event/classic-car-show-2025/",
      eventAddress:
        "Highnam Court, Gloucester, Gloucestershire GL2 8DP, United Kingdom",
        eventLat: 51.872119,
        eventLng: -2.3038669,
        eventPhone: "",
      eventEmail: "",
      eventCity: "Gloucester",
      eventPostalCode: "GL2 8DP",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/Classic-car-Poster-25.webp",
      eventCategory: ["Car Show", "Truck Show"],
      eventState: "Gloucestershire",
      eventSlug: "classic-car-show-2025-highnam-court",
      eventFeatured: false,
      eventDescription:
        "We are excited to welcome you and your classic car to the 2025 Classic Car show in aid of The Pied Piper Appeal. General admission to this event is £10 for adults. Children under 16 are free of charge and can just turn up on the day",
    },
    {
      eventTitle: "Pistons & Pretzels - UK",
      eventStartDateTime: "04052025:11:00:00",
      eventEndDateTime: "04052025:16:00:00",
      eventTicketPrice: "Free Entry",
      eventWebsite:
        "https://www.konzepthaus-consulting.com/insights/events/pistons-pretzels-uk-0",
      eventAddress:
        "Bicester Heritage, The Station Armoury, Building 123 Buckingham Rd London OX2 5HA",
        eventLat: 51.9149975,
        eventLng: -1.1431272,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Bicester",
      eventPostalCode: "OX2 5HA",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/pistons-pretzels.avif",
      eventCategory: ["Car Meet", "Classic Car"],
      eventState: "Oxfordshire",
      eventSlug: "pistons-pretzels-uk-May-2025",
      eventFeatured: false,
      eventDescription:
        "May the Fourth be with you! Pistons & Pretzels is returning to Bicester to celebrate an unforgettable gathering with the car design community. **NOTE** To enter, you must be part of the Car Design Community or a guest of a member.",
    },
    {
      eventTitle: "A British Icon - Aston Martin",
      eventStartDateTime: "03062025:11:00:00",
      eventEndDateTime: "03062025:20:00:00",
      eventTicketPrice: "£60.00",
      eventWebsite: "https://londonconcours.co.uk/",
      eventAddress:
        "The Honourable Artillery Company, Armoury House, City Road, London EC1Y 2BQ",
        eventLat: 51.5229682,
        eventLng: -0.088292,
        eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "EC1Y 2BQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/aston-martin-car-show.avif",
      eventCategory: ["Car Show"],
      eventState: "London",
      eventSlug: "aston-martin-brisith-icon",
      eventFeatured: true,
      eventDescription:
        "The display will be limited to 50 curated examples of the marque.",
    },
    {
      eventTitle: "AutoCulture 2025",
      eventStartDateTime: "13042025:10:00:00",
      eventEndDateTime: "13042025:16:00:00",
      eventTicketPrice: "£15.00 (Early Bird) + £0.38 service fee",
      eventWebsite: "https://www.autocultureshow.co.uk/",
      eventAddress: "Bawtry Rd, Doncaster DN2 6BB, UK",
      eventPhone: "",
      eventEmail: "",
      eventCity: "Doncaster",
      eventPostalCode: "DN2 6BB",
      eventCountryCode: "GB",
      eventLat: 53.5204743,
      eventLng: -1.1091487,
      eventImageUrl: "/assets/images/events/autoculture-2025.avif",
      eventCategory: ["Car Show", "Classic Cars", "Retro Cars"],
      eventState: "South Yorkshire",
      eventSlug: "autoculture-2025",
      eventFeatured: false,
      eventDescription: "AutoCulture 2025 is an automotive gathering celebrating Volkswagens, classic cars, and retro charm. Emerging from the success of Elsecar At The Races, AutoCulture stays true to its roots while expanding to welcome Classic & Retro Cars into the fold. Located at the iconic Doncaster Racecourse, the event offers an unmissable experience for car enthusiasts."
    }
  ];
};
