module.exports = function () {
  // This would typically be fetched from a headless CMS
  // For now, using static data based on the provided sample
  return [
    {
      eventTitle: "Netherby Hall Annual Car Show 2025",
      eventStartDateTime: "02082025:10:00:00",
      eventEndDateTime: "03082025:16:00:00",
      eventTicketPrice: "Adult £12.00 single day - £20.00 weekend - Group (up to 6) £45.00 single day - £70.00 weekend - Children under 16 free - Exhibitor & 1 guest £5.00",
      eventWebsite: "https://netherbyhall.co.uk/event/netherby-hall-2025-car-show-in-cumbria",
      eventAddress: "Netherby Hall, Netherby, Longtown, Carlisle, Cumbria, CA6 5PR, UK",
      eventLat: 55.035662,
      eventLng: -2.9482453,
      eventPhone: "01228 792732",
      eventEmail: "events@netherbyhall.co.uk",
      eventCity: "Longtown",
      eventPostalCode: "CA6 5PR",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/netherby-hall-car-show-2025.avif",
      eventCategory: ["Classic Cars", "Performance Cars", "Supercars", "Vintage Vehicles", "Historic Estate", "Family Event"],
      eventState: "Cumbria",
      eventSlug: "netherby-hall-annual-car-show-2025",
      eventFeatured: true,
      eventDescription: "Set in the beautiful Cumbrian countryside at historic Netherby Hall. Saturday features Performance and Super Cars, Sunday showcases Classic and Vintage vehicles (pre-2005 registration). Rare and unique classic cars with detailed vehicle histories. Includes food and drink stalls, craft stalls, stunning estate grounds, and luxury accommodation available on-site."
    },
    {
      eventTitle: "South Yorkshire Classic Car & Motorcycle Show 2025",
      eventStartDateTime: "03082025:10:00:00",
      eventEndDateTime: "03082025:16:00:00",
      eventTicketPrice: "Adult £10.50 advance (£12.50 gate) - Child (5-14) £3.50 - Exhibitor £5.50 advance (£7.50 from April)",
      eventWebsite: "https://classicshows.org/events/south-yorkshire-classic-car-motorcycle-show-3-august-2025",
      eventAddress: "Wentworth Woodhouse, Wentworth, Rotherham, South Yorkshire, S62 7TQ, UK",
      eventLat: 53.47417,
      eventLng: -1.40472,
      eventPhone: "01484 667776",
      eventEmail: "info@classicshows.org",
      eventCity: "Rotherham",
      eventPostalCode: "S62 7TQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/south-yorkshire-classic-car-motorcycle-show.avif",
      eventCategory: ["Classic Cars", "Motorcycles", "Autojumble", "Trade Stands", "Historic House"],
      eventState: "South Yorkshire",
      eventSlug: "south-yorkshire-classic-car-motorcycle-show-2025",
      eventFeatured: true,
      eventDescription: "Spectacular classic car and motorcycle show at the magnificent Wentworth Woodhouse, often listed as the largest private residence in the UK. Features wide range of classic vehicles, autojumble stalls, street food, drinks stands, and access to the stunning historic estate grounds and gardens."
    },
    {
      eventTitle: "2025 BVAC Classic",
      eventStartDateTime: "08062025:11:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "£15.00",
      eventWebsite: "https://bvac.org.uk/event/2025-bvac-classic/",
      eventAddress: "Thirlestane Castle, Lauder, Scottish Borders, TD2 6RU, UK",
      eventLat: 55.722255,
      eventLng: -2.743447,
      eventPhone: "01896 849597",
      eventEmail: "info@bvac.org.uk",
      eventCity: "Lauder",
      eventPostalCode: "TD2 6RU",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/bvac-classic-2025.avif",
      eventCategory: ["Car Show", "Classic Cars", "Family Event"],
      eventState: "Scottish Borders",
      eventSlug: "bvac-classic-2025",
      eventFeatured: true,
      eventDescription: "The 2025 BVAC Classic, celebrating its 50th anniversary, is Scotland's premier classic car show. Held at the picturesque Thirlestane Castle, the event showcases over 1,000 classic and vintage cars, live motorsport action, stunt displays, a retail village, and a variety of food and drink options, making it a perfect day out for the whole family."
    },
    {
      eventTitle: "Gloucestershire Vintage & Country Extravaganza 2025",
      eventStartDateTime: "01082025:10:00:00",
      eventEndDateTime: "03082025:17:00:00",
      eventTicketPrice: "Adult £13.50 advance (£15 gate) - Child (5-15) £4.50 advance (£5 gate) - Children under 5 free - Family ticket (2 adults, 2 children) £31.50 advance (£35 gate)",
      eventWebsite: "https://www.glosvintageextravaganza.co.uk",
      eventAddress: "South Cerney Airfield, Northmoor Lane, South Cerney, Cirencester, Gloucestershire, GL7 5QD, UK",
      eventLat: 51.6885855,
      eventLng: -1.923215,
      eventPhone: "01453 890891",
      eventEmail: "enquiries.svtec@hotmail.com",
      eventCity: "Cirencester",
      eventPostalCode: "GL7 5QD",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/glosvintageimage2025.avif",
      eventCategory: ["Steam Rally", "Vintage Transport", "Classic Cars", "Motorcycles", "Family Event", "Country Show", "50th Anniversary"],
      eventState: "Gloucestershire",
      eventSlug: "gloucestershire-vintage-country-extravaganza-2025",
      eventFeatured: true,
      eventDescription: "The 50th anniversary of the Gloucestershire Vintage & Country Extravaganza returns to South Cerney Airfield. Regarded as one of the biggest and best steam, vintage and countryside events in the UK with nearly 1000 classic cars, hundreds of motorbikes, steam engines, vintage buses, military vehicles, and much more. Features three live arenas, vintage entertainment tent with live music and dance, animal and countryside arena, vintage fairground, trade stands, craft marquee, and free vintage bus rides."
    },
    {
      eventTitle: "Folkestone and Ashford Military Show 2025",
      eventStartDateTime: "07062025:10:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "Adult £8.00 - Child £5.00 - Family £25.00",
      eventWebsite: "http://www.faams.co.uk",
      eventAddress: "Sellindge Show Ground, M20 Junction 11, Between Folkestone and Ashford, Kent, TN25 6H, UK",
      eventLat: 51.1106317,
      eventLng: 1.0258078,
      eventPhone: "07759 283833",
      eventEmail: "Info@faams.co.uk",
      eventCity: "Sellindge",
      eventPostalCode: "TN25 6H",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/folkestone-ashford-military-show-2025.avif",
      eventCategory: ["Military Show","Classic Cars","Family Event","Charity Event"],
      eventState: "Kent",
      eventSlug: "folkestone-ashford-military-show-2025",
      eventFeatured: true,
      eventDescription: "The Folkestone and Ashford Military Show is a two-day event organized by a cadet group for charity to help the Royal British Legion raise funds. Features entertainment in the marquee, arena displays, youth motorcycle display team, static displays, stalls, classic cars and motorcycles, food stalls, full funfair, and camping facilities."
    },
    {
      eventTitle: "Loch Ness Classic and Vintage Car Tour 2025",
      eventStartDateTime: "07062025:10:30:00",
      eventEndDateTime: "07062025:16:30:00",
      eventTicketPrice: "Free (Charity Donations)",
      eventWebsite: "https://lochnessclassiccartour.weebly.com",
      eventAddress: "Inverness Ice Centre, Inverness, Scotland, IV1 1RY, UK",
      eventLat: 57.4635294,
      eventLng: -4.2397648,
      eventPhone: "07774 695640",
      eventEmail: "nicol.manson@btinternet.com",
      eventCity: "Inverness",
      eventPostalCode: "IV1 1RY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/loch-ness-classic-tour-2025.avif",
      eventCategory: ["Car Tour","Classic Cars","Charity Event","Scenic Tour"],
      eventState: "Scotland",
      eventSlug: "loch-ness-classic-car-tour-2025",
      eventFeatured: true,
      eventDescription: "The Loch Ness Classic and Vintage Car Tour is a non-competitive touring event for classic, vintage, and sporting vehicles. The 160-mile route covers stunning Highland landscapes including Loch Ness, Black Isle, Easter Ross, and Sutherland. Start and finish at Inverness Ice Centre. No entry fee but entrants are encouraged to raise charity sponsorship. Public viewing available at start (10:30am) and finish (3:30pm onwards)."
    },
    {
      eventTitle: "Masters of Motoring - Classic & Sports Car Show 2025",
      eventStartDateTime: "08062025:10:00:00",
      eventEndDateTime: "08062025:16:30:00",
      eventTicketPrice: "£25.00 - £55.00",
      eventWebsite: "https://bowood.org/event/masters-of-motoring-classic-sports-car-show/",
      eventAddress: "Bowood House & Gardens, Derry Hill, Chippenham, Wiltshire, SN11 9PQ, UK",
      eventLat: 51.4290567,
      eventLng: -2.0380402,
      eventPhone: "01249 812102",
      eventEmail: "events@bowood.org",
      eventCity: "Chippenham",
      eventPostalCode: "SN11 9PQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/bowood-masters-of-motoring-classic-sports-car-show-2025.avif",
      eventCategory: ["Classic Cars","Supercars","Luxury Cars","Concours"],
      eventState: "Wiltshire",
      eventSlug: "masters-of-motoring-classic-sports-car-show-2025",
      eventFeatured: true,
      eventDescription: "Experience luxury motoring at its finest as Masters of Motoring showcases a breathtaking assembly of concours supercars, heritage classics, and modern sports cars in the prestigious setting of Bowood House. Join a community of automotive aficionados to appreciate these stunning examples that celebrate the artistry of automotive design across generations."
    },
    {
      eventTitle: "Stoke Row Steam Rally 2025",
      eventStartDateTime: "07062025:09:00:00",
      eventEndDateTime: "08062025:17:00:00",
      eventTicketPrice: "£12.00",
      eventWebsite: "https://stokerowsteamrally.com/",
      eventAddress: "Hill Bottom, Whitchurch Hill, Reading, Berkshire, RG8 7RL, UK",
      eventLat: 51.527131,
      eventLng: -1.072597,
      eventPhone: "01491 680242",
      eventEmail: "StokeRowSR@gmail.com",
      eventCity: "Reading",
      eventPostalCode: "RG8 7RL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/stoke-row-steam-rally-2025.avif",
      eventCategory: ["Steam Rally","Classic Cars","Historic Vehicles"],
      eventState: "Berkshire",
      eventSlug: "stoke-row-steam-rally-2025",
      eventFeatured: false,
      eventDescription: "Annual Stoke Row Steam Rally featuring more than 70 steam vehicles of historic importance, plus classic cars. A celebration of steam power and vintage machinery in the Berkshire countryside."
     },
     {
      eventTitle: "VSCC Harewood Hill - Climb Speed Championship Round 3 2025",
      eventStartDateTime: "08062025:09:00:00",
      eventEndDateTime: "08062025:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.vscc.co.uk/page/events?eventID=1917",
      eventAddress: "Harewood Ave, Harewood, Leeds LS17 9LA, Yorkshire",
      eventLat: 53.9051086,
      eventLng: -1.4928095,
      eventPhone: "01234 567890",
      eventEmail: "events@vscc.co.uk",
      eventCity: "Leeds",
      eventPostalCode: "TBC",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/vscc-speed-championship-2025.avif",
      eventCategory: ["Speed Championship","Hill Climb","Competition","Classic Cars"],
      eventState: "Yorkshire",
      eventSlug: "vscc-speed-championship-round-3-2025",
      eventFeatured: true,
      eventDescription: "Round 3 of the VSCC Speed Championship, hosted by friends at BARC. Set near the delightful Yorkshire dales, the whole hill is visible from the paddock, making it a popular venue for both public and competitors. A classic speed event in a stunning location."
     },
     {
      eventTitle: "Cleveleys Car Show 2025",
      eventStartDateTime: "08062025:09:00:00",
      eventEndDateTime: "08062025:16:00:00",
      eventTicketPrice: "Free",
      eventWebsite: "https://www.facebook.com/events/640080858576148/",
      eventAddress: "Town Centre and Promenade, Cleveleys, Lancashire, FY5 1PJ, UK",
      eventLat: 53.8759119,
      eventLng: -3.0337209,
      eventPhone: "",
      eventEmail: "ukwheelsevents@gmail.com",
      eventCity: "Cleveleys",
      eventPostalCode: "FY5 1PJ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/cleveleys-car-show-2025.avif",
      eventCategory: ["Classic Vehicles","Town Centre Event","Free Event"],
      eventState: "Lancashire",
      eventSlug: "cleveleys-classic-vehicle-show-2025",
      eventFeatured: true,
      eventDescription: "The Cleveleys Classic Vehicle Show turns the seaside promenade and town centre into a spectacular automotive celebration! Hundreds of stunning classic cars, bikes, and vehicles of all shapes and sizes line the seafront and fill the streets, creating an incredible display just outside Blackpool. With all the action happening right by the coast, you can enjoy brilliant shops, cafes, and restaurants while soaking up that classic seaside atmosphere - the perfect blend of motoring heritage and seaside charm!"
     },
    {
      eventTitle: "Brooklands Best of British Day 2025",
      eventStartDateTime: "26052025:10:00:00",
      eventEndDateTime: "26052025:17:00:00",
      eventTicketPrice: "£26.40",
      eventWebsite: "https://www.brooklandsmuseum.com/whats-on/best-of-british-2025",
      eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey, KT13 0SL, UK",
      eventLat: 51.354512,
      eventLng: -0.4669199,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/best-of-british-2025.avif",
      eventCategory: ["Car Show", "Motorcycle Show", "British Vehicles"],
      eventState: "Surrey",
      eventSlug: "best-of-british-2025",
      eventFeatured: false,
      eventDescription: "Enjoy a day of British vehicles with lots of family entertainment, plus Test Hill ascents! Meet Paddington™ at intervals throughout the day. There will be a huge display of British built vehicles, from the pre-war Alvis, Norton and Sunbeam right through to the latest Jaguar models. All British marques are welcome to join, independently or with a Car Club. Admission includes access to Brooklands Museum for the day. Normal Museum Admission applies. Children under 4 go free. Members go free. Gates open at 9am for classic vehicles via Campbell Gate off Brooklands Road."
   },
   {
    eventTitle: "Mopar Muscle 2025",
    eventStartDateTime: "25052025:10:00:00",
    eventEndDateTime: "25052025:17:00:00",
    eventTicketPrice: "£26.40",
    eventWebsite: "https://www.brooklandsmuseum.com/whats-on/mopar-muscle-day",
    eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey",
    eventLat: 51.354711,
    eventLng: -0.464371,
    eventPhone: "01932 857381",
    eventEmail: "info@brooklandsmuseum.com",
    eventCity: "Weybridge",
    eventPostalCode: "KT13 0SL",
    eventCountryCode: "GB",
    eventImageUrl: "/assets/images/events/mopar-muscle-2025.avif",
    eventCategory: ["Car Show", "Classic Cars", "American Cars", "Family Event"],
    eventState: "Surrey",
    eventSlug: "mopar-muscle-2025",
    eventFeatured: true,
    eventDescription: "Enjoy a display of MOPAR Muscle cars on the Finishing Straight and Banking. Expect a feast of chrome and colour with Chryslers, Dodges, Plymouths and other MOPAR Muscle cars, many beautifully restored with engines up to 9,000ccs. The event includes food stalls, trade stands, live music and access to all Brooklands Museum exhibits for the day."
    },
    {
      eventTitle: "Brooklands Drive It Day 2025",
      eventStartDateTime: "27052025:10:00:00",
      eventEndDateTime: "27052025:17:00:00",
      eventTicketPrice: "£26.40",
      eventWebsite: "https://brooklandsmuseum.seetickets.com/event/event-day-drive-it-day/brooklands-museum/3230083",
      eventAddress: "Brooklands Museum, Brooklands Drive, Weybridge, Surrey, KT13 0SL, UK",
      eventLat: 51.354512,
      eventLng: -0.4669199,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/brookands-drive-it-day-2025.avif",
      eventCategory: ["Car Show", "Motorcycle Show", "Drive It Day"],
      eventState: "Surrey",
      eventSlug: "drive-it-day-2025",
      eventFeatured: true,
      eventDescription: "Join this year's Drive It Day along with Ride It Day for the Motorcycle Community. Bring your classic car or motorcycle to take part in this year's Drive It Day, in aid of the NSPCC's Childline®, to raise money to support vulnerable children. Pre-31 July 1995 vehicles are welcome. Gates open at 9am for classic vehicles via Campbell Gate off Brooklands Road. The Museum and Sunbeam Café open at 10am. Child Entry (4-17 Yrs) (W/ DONATION)	£11.00"
    },
    {
      eventTitle: "Classic Car Show 2025",
      eventStartDateTime: "08062025:10:00:00",
      eventEndDateTime: "08062025:16:00:00",
      eventTicketPrice: "£10.00",
      eventWebsite:
        "https://piedpiperappeal.co.uk/event/classic-car-show-2025/",
      eventAddress:
        "Highnam Court, Gloucester, Gloucestershire GL2 8DP, United Kingdom",
        eventLat: 51.872119,
        eventLng: -2.3038669,
        eventPhone: "",
      eventEmail: "",
      eventCity: "Gloucester",
      eventPostalCode: "GL2 8DP",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/Classic-car-Poster-25.webp",
      eventCategory: ["Car Show", "Truck Show"],
      eventState: "Gloucestershire",
      eventSlug: "classic-car-show-2025-highnam-court",
      eventFeatured: false,
      eventDescription:
        "We are excited to welcome you and your classic car to the 2025 Classic Car show in aid of The Pied Piper Appeal. General admission to this event is £10 for adults. Children under 16 are free of charge and can just turn up on the day",
    },
    {
      eventTitle: "Pistons & Pretzels - UK",
      eventStartDateTime: "04052025:11:00:00",
      eventEndDateTime: "04052025:16:00:00",
      eventTicketPrice: "Free Entry",
      eventWebsite:
        "https://www.konzepthaus-consulting.com/insights/events/pistons-pretzels-uk-0",
      eventAddress:
        "Bicester Heritage, The Station Armoury, Building 123 Buckingham Rd London OX2 5HA",
        eventLat: 51.9149975,
        eventLng: -1.1431272,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Bicester",
      eventPostalCode: "OX2 5HA",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/pistons-pretzels.avif",
      eventCategory: ["Car Meet", "Classic Car"],
      eventState: "Oxfordshire",
      eventSlug: "pistons-pretzels-uk-May-2025",
      eventFeatured: false,
      eventDescription:
        "May the Fourth be with you! Pistons & Pretzels is returning to Bicester to celebrate an unforgettable gathering with the car design community. **NOTE** To enter, you must be part of the Car Design Community or a guest of a member.",
    },
    {
      eventTitle: "A British Icon - Aston Martin",
      eventStartDateTime: "03062025:11:00:00",
      eventEndDateTime: "03062025:20:00:00",
      eventTicketPrice: "£60.00",
      eventWebsite: "https://londonconcours.co.uk/",
      eventAddress:
        "The Honourable Artillery Company, Armoury House, City Road, London EC1Y 2BQ",
        eventLat: 51.5229682,
        eventLng: -0.088292,
        eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "EC1Y 2BQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/aston-martin-car-show.avif",
      eventCategory: ["Car Show"],
      eventState: "London",
      eventSlug: "aston-martin-brisith-icon",
      eventFeatured: true,
      eventDescription:
        "The display will be limited to 50 curated examples of the marque.",
    },
    {
      eventTitle: "AutoCulture 2025",
      eventStartDateTime: "13042025:10:00:00",
      eventEndDateTime: "13042025:16:00:00",
      eventTicketPrice: "£15.00 (Early Bird) + £0.38 service fee",
      eventWebsite: "https://www.autocultureshow.co.uk/",
      eventAddress: "Bawtry Rd, Doncaster DN2 6BB, UK",
      eventPhone: "",
      eventEmail: "",
      eventCity: "Doncaster",
      eventPostalCode: "DN2 6BB",
      eventCountryCode: "GB",
      eventLat: 53.5204743,
      eventLng: -1.1091487,
      eventImageUrl: "/assets/images/events/autoculture-2025.avif",
      eventCategory: ["Car Show", "Classic Cars", "Retro Cars"],
      eventState: "South Yorkshire",
      eventSlug: "autoculture-2025",
      eventFeatured: false,
      eventDescription: "AutoCulture 2025 is an automotive gathering celebrating Volkswagens, classic cars, and retro charm. Emerging from the success of Elsecar At The Races, AutoCulture stays true to its roots while expanding to welcome Classic & Retro Cars into the fold. Located at the iconic Doncaster Racecourse, the event offers an unmissable experience for car enthusiasts."
    },

    // =============================================================
    // ============ 2026 EVENTS (June – December 2026) ============
    // =============================================================
    // Images default to the brand-green placeholder; replace with bespoke
    // assets in /assets/images/events/ as they become available.

    // ---- JUNE 2026 ----
    {
      eventTitle: "Classic & Performance Car Spectacular — Tatton Park",
      eventStartDateTime: "06062026:09:30:00",
      eventEndDateTime: "07062026:16:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://tickets.mortonsevents.co.uk/event/31",
      eventAddress: "Tatton Park, Ashley Road, Knutsford, Cheshire, WA16 6QN",
      eventLat: 53.3290,
      eventLng: -2.3866,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Knutsford",
      eventPostalCode: "WA16 6QN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Cheshire",
      eventSlug: "tatton-park-classic-performance-spectacular-2026",
      eventFeatured: true,
      eventDescription: "Over 2,000 classic cars displayed by 90+ car clubs and private exhibitors in the parkland of Tatton Park, with autojumble, food and family entertainment."
    },
    {
      eventTitle: "MotoFest Coventry 2026",
      eventStartDateTime: "06062026:10:00:00",
      eventEndDateTime: "07062026:18:00:00",
      eventTicketPrice: "Free",
      eventWebsite: "https://www.coventrymotofest.com/",
      eventAddress: "Coventry City Centre, Coventry, CV1 1GS",
      eventLat: 52.4068,
      eventLng: -1.5197,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Coventry",
      eventPostalCode: "CV1 1GS",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Festival", "Family Event"],
      eventState: "West Midlands",
      eventSlug: "motofest-coventry-2026",
      eventFeatured: true,
      eventDescription: "Free city-centre celebration of Coventry's automotive heritage with the MotoFest Classic display of classic and heritage vehicles, ring-road parades and live demonstrations."
    },
    {
      eventTitle: "Beaulieu Simply Ford 2026",
      eventStartDateTime: "07062026:10:00:00",
      eventEndDateTime: "07062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Marque Rally"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-ford-2026",
      eventFeatured: false,
      eventDescription: "Sunday rally on the Beaulieu lawns celebrating Fords from Cortina, Capri and Escort through to Mustang and modern hot hatches."
    },
    {
      eventTitle: "London Concours 2026",
      eventStartDateTime: "09062026:10:00:00",
      eventEndDateTime: "11062026:17:30:00",
      eventTicketPrice: "From £45 (afternoon) / £65 day ticket",
      eventWebsite: "https://londonconcours.co.uk/",
      eventAddress: "Honourable Artillery Company, Armoury House, City Road, London, EC1Y 2BQ",
      eventLat: 51.5256,
      eventLng: -0.0876,
      eventPhone: "",
      eventEmail: "info@londonconcours.co.uk",
      eventCity: "London",
      eventPostalCode: "EC1Y 2BQ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Concours", "Luxury"],
      eventState: "Greater London",
      eventSlug: "london-concours-2026",
      eventFeatured: true,
      eventDescription: "Three-day luxury automotive garden party in the heart of the City of London, with daily themes including Porsche, Jaguar XK and supercars."
    },
    {
      eventTitle: "Cholmondeley Pageant of Power 2026",
      eventStartDateTime: "12062026:09:30:00",
      eventEndDateTime: "14062026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://sportshire.co.uk/cholmondeley-pageant-of-power/",
      eventAddress: "Cholmondeley Castle, Malpas, Cheshire, SY14 8AH",
      eventLat: 53.0628,
      eventLng: -2.7250,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Malpas",
      eventPostalCode: "SY14 8AH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Festival", "Hillclimb", "Family Event"],
      eventState: "Cheshire",
      eventSlug: "cholmondeley-pageant-of-power-2026",
      eventFeatured: true,
      eventDescription: "Three days of motorsport demonstrations in the grounds of Cholmondeley Castle, with cars, bikes and powerboats taking to land and lake."
    },
    {
      eventTitle: "Hever Castle Cars at the Castle 2026",
      eventStartDateTime: "13062026:10:30:00",
      eventEndDateTime: "14062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.hevercastle.co.uk/whats-on/cars-at-the-castle-2026/",
      eventAddress: "Hever Castle, Hever Road, Edenbridge, Kent, TN8 7NG",
      eventLat: 51.1849,
      eventLng: 0.1058,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Edenbridge",
      eventPostalCode: "TN8 7NG",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Family Event", "Historic Estate"],
      eventState: "Kent",
      eventSlug: "hever-castle-cars-at-the-castle-2026",
      eventFeatured: false,
      eventDescription: "An eclectic gathering of restored vintage models, sports cars and club displays in the stunning grounds of Hever Castle, Anne Boleyn's childhood home."
    },
    {
      eventTitle: "HSCC Cadwell Park 2026",
      eventStartDateTime: "13062026:09:00:00",
      eventEndDateTime: "14062026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://hscc.org.uk/racing-calendar-2026/",
      eventAddress: "Cadwell Park Circuit, Louth, Lincolnshire, LN11 9SE",
      eventLat: 53.3097,
      eventLng: -0.0497,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Louth",
      eventPostalCode: "LN11 9SE",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing"],
      eventState: "Lincolnshire",
      eventSlug: "hscc-cadwell-park-june-2026",
      eventFeatured: false,
      eventDescription: "HSCC historic race meeting on the twisting parkland Lincolnshire circuit with packed grids of Formula Junior, Formula Ford and historic touring cars."
    },
    {
      eventTitle: "Bo'ness Hill Climb Revival 2026",
      eventStartDateTime: "13062026:10:00:00",
      eventEndDateTime: "14062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.bonessrevival.co.uk/",
      eventAddress: "Kinneil Estate, Bo'ness, West Lothian, EH51 0PR",
      eventLat: 56.0153,
      eventLng: -3.6253,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Bo'ness",
      eventPostalCode: "EH51 0PR",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Hillclimb", "Historic Racing"],
      eventState: "Scotland",
      eventSlug: "boness-hill-climb-revival-2026",
      eventFeatured: false,
      eventDescription: "Historic hill climb at Scotland's oldest permanent motorsport venue, complete with classic car show, motorcycle parades and Jim Clark tributes."
    },
    {
      eventTitle: "Prescott Motorsport Festival 2026",
      eventStartDateTime: "13062026:08:30:00",
      eventEndDateTime: "14062026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.prescotthillclimb.co.uk/event-calendar",
      eventAddress: "Prescott Speed Hill Climb, Gotherington, Cheltenham, Gloucestershire, GL52 9RD",
      eventLat: 51.9709,
      eventLng: -2.0383,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Cheltenham",
      eventPostalCode: "GL52 9RD",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Hillclimb", "Festival"],
      eventState: "Gloucestershire",
      eventSlug: "prescott-motorsport-festival-2026",
      eventFeatured: false,
      eventDescription: "Grassroots motorsport celebration weekend on Prescott Hill, incorporating the National Ferrari Owners' Day among the timed runs."
    },
    {
      eventTitle: "Lake District Classic & Performance Motor Show 2026",
      eventStartDateTime: "14062026:10:00:00",
      eventEndDateTime: "14062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://greatbritishmotorshows.com/event/lake-district-classic-and-performacne-motor-show/",
      eventAddress: "Hutton-in-the-Forest, Skelton, Penrith, Cumbria, CA11 9TH",
      eventLat: 54.7283,
      eventLng: -2.8056,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Penrith",
      eventPostalCode: "CA11 9TH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Family Event", "Historic Estate"],
      eventState: "Cumbria",
      eventSlug: "lake-district-classic-performance-motor-show-2026",
      eventFeatured: false,
      eventDescription: "Classic and performance cars displayed against the spectacular North Lakes scenery in the grounds of historic Hutton-in-the-Forest."
    },
    {
      eventTitle: "National Mini Day at Beaulieu 2026",
      eventStartDateTime: "14062026:10:00:00",
      eventEndDateTime: "14062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/mini-cooper-register-rally/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Hampshire",
      eventSlug: "national-mini-day-beaulieu-2026",
      eventFeatured: false,
      eventDescription: "The Mini Cooper Register's flagship rally at Beaulieu — the club's 40th birthday — with hundreds of Minis across every era and a Concours d'Elegance."
    },
    {
      eventTitle: "Beaulieu Custom & American Show 2026",
      eventStartDateTime: "21062026:10:00:00",
      eventEndDateTime: "21062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/custom-and-american-show/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Hot Rods", "American Cars"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-custom-american-show-2026",
      eventFeatured: false,
      eventDescription: "Father's Day showcase of hot rods, custom builds and American classics on the lawns at the National Motor Museum."
    },
    {
      eventTitle: "Brooklands Japanese Day 2026",
      eventStartDateTime: "21062026:10:00:00",
      eventEndDateTime: "21062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.brooklandsmuseum.com/whats-on/",
      eventAddress: "Brooklands Museum, Brooklands Road, Weybridge, Surrey, KT13 0SL",
      eventLat: 51.3478,
      eventLng: -0.4631,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Marque Rally"],
      eventState: "Surrey",
      eventSlug: "brooklands-japanese-day-2026",
      eventFeatured: false,
      eventDescription: "Marque-themed open day at Brooklands celebrating Japanese motoring with club displays, demonstrations and full museum access."
    },
    {
      eventTitle: "Goodwood Breakfast Club: GRRC Members 2026",
      eventStartDateTime: "22062026:08:00:00",
      eventEndDateTime: "22062026:12:00:00",
      eventTicketPrice: "GRRC members only",
      eventWebsite: "https://www.goodwood.com/motorsport/breakfast-club/",
      eventAddress: "Goodwood Motor Circuit, Chichester, West Sussex, PO18 0PH",
      eventLat: 50.8585,
      eventLng: -0.7508,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chichester",
      eventPostalCode: "PO18 0PH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Members Event"],
      eventState: "West Sussex",
      eventSlug: "goodwood-breakfast-club-grrc-june-2026",
      eventFeatured: false,
      eventDescription: "Members-only Breakfast Club gathering bringing together a curated display of historic and competition machinery at the Goodwood Motor Circuit."
    },
    {
      eventTitle: "Heveningham Concours of Elegance 2026",
      eventStartDateTime: "27062026:10:00:00",
      eventEndDateTime: "28062026:17:30:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://heveninghamconcours.com/",
      eventAddress: "Heveningham Hall, Heveningham, Halesworth, Suffolk, IP19 0PN",
      eventLat: 52.2949,
      eventLng: 1.4583,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Halesworth",
      eventPostalCode: "IP19 0PN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Concours", "Country Fair"],
      eventState: "Suffolk",
      eventSlug: "heveningham-concours-of-elegance-2026",
      eventFeatured: true,
      eventDescription: "Around 50 of the world's finest motor cars and historic propeller aircraft gather at Capability Brown's Heveningham Hall for the country fair concours."
    },
    {
      eventTitle: "Beaulieu Simply French 2026",
      eventStartDateTime: "28062026:10:00:00",
      eventEndDateTime: "28062026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Marque Rally"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-french-2026",
      eventFeatured: false,
      eventDescription: "Citroëns, Renaults, Peugeots and other French classics gather on the Beaulieu lawns for a relaxed marque-themed Sunday."
    },

    // ---- JULY 2026 ----
    {
      eventTitle: "Cars in the Park, Lichfield 2026",
      eventStartDateTime: "04072026:09:30:00",
      eventEndDateTime: "05072026:17:00:00",
      eventTicketPrice: "Free for spectators",
      eventWebsite: "http://www.carsinthepark.com/",
      eventAddress: "Beacon Park, Beacon Street, Lichfield, Staffordshire, WS13 7AA",
      eventLat: 52.6864,
      eventLng: -1.8336,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Lichfield",
      eventPostalCode: "WS13 7AA",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Staffordshire",
      eventSlug: "cars-in-the-park-lichfield-2026",
      eventFeatured: true,
      eventDescription: "One of the largest classic car gatherings in Great Britain — 2,000+ classics, vintage and new vehicles spread across two days in Beacon Park."
    },
    {
      eventTitle: "Beaulieu Simply Land Rover 2026",
      eventStartDateTime: "05072026:10:00:00",
      eventEndDateTime: "05072026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "4x4"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-land-rover-2026",
      eventFeatured: false,
      eventDescription: "Series I, Defenders, Discoverys and modern Land Rovers fill the New Forest lawns for a celebration of the iconic British 4x4."
    },
    {
      eventTitle: "Goodwood Festival of Speed 2026",
      eventStartDateTime: "09072026:07:30:00",
      eventEndDateTime: "12072026:19:00:00",
      eventTicketPrice: "From £60 (Thursday)",
      eventWebsite: "https://www.goodwood.com/motorsport/festival-of-speed/",
      eventAddress: "Goodwood House, Goodwood, Chichester, West Sussex, PO18 0PH",
      eventLat: 50.8585,
      eventLng: -0.7508,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chichester",
      eventPostalCode: "PO18 0PH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Motoring Festival", "Hillclimb", "Family Event"],
      eventState: "West Sussex",
      eventSlug: "goodwood-festival-of-speed-2026",
      eventFeatured: true,
      eventDescription: "The world's largest motoring garden party returns themed 'The Rivals: Epic Racing Duels', reuniting the 1966 Le Mans-winning Ford GT MkIIs and marking 50 years since Hunt vs Lauda."
    },
    {
      eventTitle: "Atwell-Wilson Motor Museum Road Run 2026",
      eventStartDateTime: "11072026:10:00:00",
      eventEndDateTime: "11072026:14:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://atwellwilson.org.uk/",
      eventAddress: "Atwell-Wilson Motor Museum, Stockley Lane, Calne, Wiltshire, SN11 0NF",
      eventLat: 51.4324,
      eventLng: -2.0073,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Calne",
      eventPostalCode: "SN11 0NF",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Drive", "Road Run"],
      eventState: "Wiltshire",
      eventSlug: "atwell-wilson-road-run-2026",
      eventFeatured: false,
      eventDescription: "40-mile classic road run through the Wiltshire countryside, organised by the Atwell-Wilson Motor Museum for up to 30 road-legal classics."
    },
    {
      eventTitle: "Atwell-Wilson Motor Museum Classic Vehicle Show 2026",
      eventStartDateTime: "12072026:10:00:00",
      eventEndDateTime: "12072026:17:00:00",
      eventTicketPrice: "Adults £15, child £5",
      eventWebsite: "https://atwellwilson.org.uk/",
      eventAddress: "Atwell-Wilson Motor Museum, Stockley Lane, Calne, Wiltshire, SN11 0NF",
      eventLat: 51.4324,
      eventLng: -2.0073,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Calne",
      eventPostalCode: "SN11 0NF",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Wiltshire",
      eventSlug: "atwell-wilson-classic-vehicle-show-2026",
      eventFeatured: false,
      eventDescription: "23rd annual classic show with 100+ exhibits including Williams Formula 1 cars, retro music and food stalls in the museum grounds."
    },
    {
      eventTitle: "Shelsley Walsh Classic Nostalgia 2026",
      eventStartDateTime: "18072026:08:00:00",
      eventEndDateTime: "19072026:17:00:00",
      eventTicketPrice: "From £22 (Early Bird)",
      eventWebsite: "https://www.shelsleywalsh.com/events-1/classic-nostalgia-2026",
      eventAddress: "Shelsley Walsh Hill Climb, Shelsley Walsh, Worcester, Worcestershire, WR6 6RP",
      eventLat: 52.2728,
      eventLng: -2.3711,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Worcester",
      eventPostalCode: "WR6 6RP",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Hillclimb", "Festival"],
      eventState: "Worcestershire",
      eventSlug: "shelsley-walsh-classic-nostalgia-2026",
      eventFeatured: true,
      eventDescription: "The world's oldest motorsport venue hosts a vintage-themed weekend with racing cars, rally machines and a garden party atmosphere focused on pre-1976 cars."
    },
    {
      eventTitle: "Classics on the Common 2026",
      eventStartDateTime: "22072026:16:00:00",
      eventEndDateTime: "22072026:21:00:00",
      eventTicketPrice: "Free for spectators",
      eventWebsite: "https://www.classicsonthecommon.com/",
      eventAddress: "Harpenden Common, Harpenden, Hertfordshire, AL5 2AX",
      eventLat: 51.8095,
      eventLng: -0.3527,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Harpenden",
      eventPostalCode: "AL5 2AX",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Hertfordshire",
      eventSlug: "classics-on-the-common-2026",
      eventFeatured: false,
      eventDescription: "Up to 1,000 classic cars, motorcycles and scooters gather on Harpenden Common for one of the UK's largest one-day classic shows, organised by Rotary in Harpenden."
    },
    {
      eventTitle: "BRDC Classic at Silverstone 2026",
      eventStartDateTime: "24072026:09:00:00",
      eventEndDateTime: "26072026:18:30:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.silverstone.co.uk/events/brdc-classic",
      eventAddress: "Silverstone Circuit, Towcester, Northamptonshire, NN12 8TN",
      eventLat: 52.0786,
      eventLng: -1.0169,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Towcester",
      eventPostalCode: "NN12 8TN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Motoring Festival"],
      eventState: "Northamptonshire",
      eventSlug: "brdc-classic-silverstone-2026",
      eventFeatured: true,
      eventDescription: "Three-day historic racing festival hosted by the British Racing Drivers' Club, featuring new 'GP Icons' and 'Endurance Icons' grids alongside car club displays."
    },
    {
      eventTitle: "Hagerty Festival of the Unexceptional 2026",
      eventStartDateTime: "25072026:07:30:00",
      eventEndDateTime: "25072026:17:00:00",
      eventTicketPrice: "£25 adult, under-15s free",
      eventWebsite: "https://www.hagerty.co.uk/official-events/hagerty-festival-of-the-unexceptional/",
      eventAddress: "Grimsthorpe Castle, Grimsthorpe, Bourne, Lincolnshire, PE10 0LY",
      eventLat: 52.8232,
      eventLng: -0.4458,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Bourne",
      eventPostalCode: "PE10 0LY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Concours", "Family Event"],
      eventState: "Lincolnshire",
      eventSlug: "hagerty-festival-of-the-unexceptional-2026",
      eventFeatured: true,
      eventDescription: "A celebration of automotive history's most marvellously mundane machines, with the Concours de L'Ordinaire judging cars built between 1971 and 2001."
    },
    {
      eventTitle: "Goodwood Breakfast Club: July 2026",
      eventStartDateTime: "26072026:08:00:00",
      eventEndDateTime: "26072026:12:00:00",
      eventTicketPrice: "Free (ticket required)",
      eventWebsite: "https://www.goodwood.com/motorsport/breakfast-club/",
      eventAddress: "Goodwood Motor Circuit, Chichester, West Sussex, PO18 0PH",
      eventLat: 50.8585,
      eventLng: -0.7508,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chichester",
      eventPostalCode: "PO18 0PH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show"],
      eventState: "West Sussex",
      eventSlug: "goodwood-breakfast-club-july-2026",
      eventFeatured: false,
      eventDescription: "Sunday morning Breakfast Club at the Goodwood Motor Circuit with curated displays celebrating a specific automotive theme."
    },
    {
      eventTitle: "Brooklands Summer Classic Gathering & Autojumble 2026",
      eventStartDateTime: "26072026:10:00:00",
      eventEndDateTime: "26072026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.brooklandsmuseum.com/whats-on/",
      eventAddress: "Brooklands Museum, Brooklands Road, Weybridge, Surrey, KT13 0SL",
      eventLat: 51.3478,
      eventLng: -0.4631,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Autojumble", "Club Show"],
      eventState: "Surrey",
      eventSlug: "brooklands-summer-classic-gathering-autojumble-2026",
      eventFeatured: false,
      eventDescription: "Summer Classic Gathering at the original home of British motorsport, paired with an autojumble of parts, spares and memorabilia."
    },

    // ---- AUGUST 2026 ----
    {
      eventTitle: "Beaulieu Supercar Weekend 2026",
      eventStartDateTime: "01082026:10:00:00",
      eventEndDateTime: "02082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/beaulieu-supercar-weekend/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Supercars", "Family Event"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-supercar-weekend-2026",
      eventFeatured: false,
      eventDescription: "Two-day showcase of supercars and modern classics across the Beaulieu lawns, with displays from manufacturers, owners' clubs and private collectors."
    },
    {
      eventTitle: "Helmingham Hall Festival of Classic & Sports Cars 2026",
      eventStartDateTime: "02082026:10:00:00",
      eventEndDateTime: "02082026:17:00:00",
      eventTicketPrice: "From £12 advance",
      eventWebsite: "https://www.helmingham.com/events/the-festival-of-classic-sports-cars/",
      eventAddress: "Helmingham Hall, Helmingham, Stowmarket, Suffolk, IP14 6EF",
      eventLat: 52.1928,
      eventLng: 1.1325,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Stowmarket",
      eventPostalCode: "IP14 6EF",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Festival", "Family Event"],
      eventState: "Suffolk",
      eventSlug: "helmingham-hall-festival-classic-sports-cars-2026",
      eventFeatured: false,
      eventDescription: "1,200+ classics fill the grounds of moated Helmingham Hall, with driveway runs, swing dancing, birds of prey and live music."
    },
    {
      eventTitle: "Brooklands Grand Prix Centenary Event 2026",
      eventStartDateTime: "08082026:10:00:00",
      eventEndDateTime: "08082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.brooklandsmuseum.com/discover/latest-news/brooklands-museums-2026-events-calendar-grand-prix-centenary/",
      eventAddress: "Brooklands Museum, Brooklands Road, Weybridge, Surrey, KT13 0SL",
      eventLat: 51.3478,
      eventLng: -0.4631,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Centenary"],
      eventState: "Surrey",
      eventSlug: "brooklands-grand-prix-centenary-2026",
      eventFeatured: true,
      eventDescription: "A special event honouring the 100th anniversary of Britain's first Grand Prix, held at Brooklands in 1926."
    },
    {
      eventTitle: "HSCC Castle Combe 60th Anniversary 2026",
      eventStartDateTime: "08082026:09:00:00",
      eventEndDateTime: "09082026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://castlecombecircuit.co.uk/hscc-60-summer-2026/",
      eventAddress: "Castle Combe Circuit, Chippenham, Wiltshire, SN14 7EY",
      eventLat: 51.4933,
      eventLng: -2.2150,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chippenham",
      eventPostalCode: "SN14 7EY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Anniversary"],
      eventState: "Wiltshire",
      eventSlug: "hscc-castle-combe-60th-anniversary-2026",
      eventFeatured: false,
      eventDescription: "HSCC's 60th birthday celebration at the venue of its first race, with FF1600, GTs, Saloon Cars and Hot Hatch grids over the weekend."
    },
    {
      eventTitle: "Festival Italia at Brands Hatch 2026",
      eventStartDateTime: "09082026:09:00:00",
      eventEndDateTime: "09082026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.brandshatch.co.uk/2026/august/festival-italia",
      eventAddress: "Brands Hatch Circuit, Fawkham, Longfield, Kent, DA3 8NG",
      eventLat: 51.3578,
      eventLng: 0.2614,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Longfield",
      eventPostalCode: "DA3 8NG",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Italian Cars", "Historic Racing"],
      eventState: "Kent",
      eventSlug: "festival-italia-brands-hatch-2026",
      eventFeatured: false,
      eventDescription: "A day devoted to the passion, style and performance of Italian motoring, with Ferrari, Alfa Romeo and Fiat racing, supercar displays and a free grid walk."
    },
    {
      eventTitle: "Tatton Park Classic & Retro Car Revival 2026",
      eventStartDateTime: "15082026:10:00:00",
      eventEndDateTime: "16082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.theclassiccarshows.com/2026/05/07/classic-retro-car-revival-returns-to-tatton-park-for-its-second-year/",
      eventAddress: "Tatton Park, Ashley Road, Knutsford, Cheshire, WA16 6QN",
      eventLat: 53.3290,
      eventLng: -2.3866,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Knutsford",
      eventPostalCode: "WA16 6QN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Retro Cars", "Family Event"],
      eventState: "Cheshire",
      eventSlug: "tatton-park-classic-retro-revival-2026",
      eventFeatured: false,
      eventDescription: "Two-day classic and retro car celebration in Tatton Park's Cheshire parkland, featuring club displays and trade stands."
    },
    {
      eventTitle: "Beaulieu Simply Jaguar 2026",
      eventStartDateTime: "16082026:10:00:00",
      eventEndDateTime: "16082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Marque Rally"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-jaguar-2026",
      eventFeatured: false,
      eventDescription: "Jaguars from XK and E-Type to modern F-Type fill Beaulieu's lawns for a relaxed marque-themed Sunday rally."
    },
    {
      eventTitle: "Beaulieu Simply Aston Martin 2026",
      eventStartDateTime: "23082026:10:00:00",
      eventEndDateTime: "23082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Marque Rally"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-aston-martin-2026",
      eventFeatured: false,
      eventDescription: "Aston Martin Owners Club join as show partner with a special display celebrating 25 years of the V12 Vanquish."
    },
    {
      eventTitle: "CarFest 2026 at Silverstone",
      eventStartDateTime: "28082026:09:00:00",
      eventEndDateTime: "30082026:23:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://carfest.org/",
      eventAddress: "Silverstone Circuit, Towcester, Northamptonshire, NN12 8TN",
      eventLat: 52.0786,
      eventLng: -1.0169,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Towcester",
      eventPostalCode: "NN12 8TN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Family Event", "Music Festival"],
      eventState: "Northamptonshire",
      eventSlug: "carfest-silverstone-2026",
      eventFeatured: true,
      eventDescription: "Chris Evans' family festival of cars and music makes its Silverstone debut, blending classic car displays, demonstrations and headline music for children's charities."
    },
    {
      eventTitle: "Oulton Park Gold Cup 2026",
      eventStartDateTime: "29082026:09:00:00",
      eventEndDateTime: "31082026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.oultonpark.co.uk/2026/august/gold-cup",
      eventAddress: "Oulton Park Circuit, Little Budworth, Tarporley, Cheshire, CW6 9BW",
      eventLat: 53.1808,
      eventLng: -2.6147,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Tarporley",
      eventPostalCode: "CW6 9BW",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Motoring Festival"],
      eventState: "Cheshire",
      eventSlug: "oulton-park-gold-cup-2026",
      eventFeatured: true,
      eventDescription: "HSCC's flagship August Bank Holiday meeting with Historic Grand Prix cars, Formula 5000 and the Derek Bell Trophy."
    },
    {
      eventTitle: "Knebworth Classic Motor Show 2026",
      eventStartDateTime: "30082026:10:00:00",
      eventEndDateTime: "31082026:16:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://knebworthhouse.com/Event/classic-motor-show/",
      eventAddress: "Knebworth Park, Knebworth House, Stevenage, Hertfordshire, SG1 2AX",
      eventLat: 51.8636,
      eventLng: -0.1928,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Stevenage",
      eventPostalCode: "SG1 2AX",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Club Show", "Family Event"],
      eventState: "Hertfordshire",
      eventSlug: "knebworth-classic-motor-show-2026",
      eventFeatured: false,
      eventDescription: "Bank Holiday classic motor show in the parkland of Knebworth House, featuring car club displays, autojumble and family entertainment."
    },
    {
      eventTitle: "Lavenham Classics Motor Show 2026",
      eventStartDateTime: "30082026:10:00:00",
      eventEndDateTime: "30082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://lavenhamclassics.com/",
      eventAddress: "Lavenham Recreation Ground, Lavenham, Suffolk, CO10 9QT",
      eventLat: 52.1086,
      eventLng: 0.7964,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Lavenham",
      eventPostalCode: "CO10 9QT",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Village Show", "Family Event"],
      eventState: "Suffolk",
      eventSlug: "lavenham-classics-motor-show-2026",
      eventFeatured: false,
      eventDescription: "Eclectic gathering of classics on the village recreation ground next to medieval Lavenham, with food stalls and an annual Bank Holiday community feel."
    },
    {
      eventTitle: "Brooklands American Day 2026",
      eventStartDateTime: "30082026:10:00:00",
      eventEndDateTime: "30082026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.brooklandsmuseum.com/whats-on/",
      eventAddress: "Brooklands Museum, Brooklands Road, Weybridge, Surrey, KT13 0SL",
      eventLat: 51.3478,
      eventLng: -0.4631,
      eventPhone: "01932 857381",
      eventEmail: "info@brooklandsmuseum.com",
      eventCity: "Weybridge",
      eventPostalCode: "KT13 0SL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "American Cars", "Club Show"],
      eventState: "Surrey",
      eventSlug: "brooklands-american-day-2026",
      eventFeatured: false,
      eventDescription: "Marque-themed day at Brooklands celebrating American cars with hot rods, muscle cars and pre-war classics on display."
    },

    // ---- SEPTEMBER 2026 ----
    {
      eventTitle: "Salon Privé Concours 2026 at Blenheim Palace",
      eventStartDateTime: "02092026:10:00:00",
      eventEndDateTime: "06092026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.salonpriveconcours.com/",
      eventAddress: "Blenheim Palace, Woodstock, Oxfordshire, OX20 1PP",
      eventLat: 51.8414,
      eventLng: -1.3614,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Woodstock",
      eventPostalCode: "OX20 1PP",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Concours", "Luxury"],
      eventState: "Oxfordshire",
      eventSlug: "salon-prive-concours-blenheim-2026",
      eventFeatured: true,
      eventDescription: "Five days of concours, supercars, luxury brands and fine dining in the grounds of Blenheim Palace, with the Aviva Private Clients Concours judged on 2–3 September."
    },
    {
      eventTitle: "Concours of Elegance Hampton Court 2026",
      eventStartDateTime: "04092026:10:00:00",
      eventEndDateTime: "06092026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://concoursofelegance.co.uk/",
      eventAddress: "Hampton Court Palace, East Molesey, Surrey, KT8 9AU",
      eventLat: 51.4036,
      eventLng: -0.3378,
      eventPhone: "",
      eventEmail: "",
      eventCity: "East Molesey",
      eventPostalCode: "KT8 9AU",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Concours", "Luxury"],
      eventState: "Surrey",
      eventSlug: "concours-of-elegance-hampton-court-2026",
      eventFeatured: true,
      eventDescription: "Sixty of the rarest cars in the world gather in the Fountain Gardens at Hampton Court Palace, alongside special features, club displays and luxury exhibitors."
    },
    {
      eventTitle: "Castle Combe Autumn Classic 2026",
      eventStartDateTime: "12092026:09:00:00",
      eventEndDateTime: "13092026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://castlecombecircuit.co.uk/autumn-classic-2026/",
      eventAddress: "Castle Combe Circuit, Chippenham, Wiltshire, SN14 7EY",
      eventLat: 51.4933,
      eventLng: -2.2150,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chippenham",
      eventPostalCode: "SN14 7EY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Festival"],
      eventState: "Wiltshire",
      eventSlug: "castle-combe-autumn-classic-2026",
      eventFeatured: true,
      eventDescription: "Historic racing festival celebrating 50 years of Castle Combe Circuit Ltd, with packed grids of pre-war, '50s, '60s and '70s machinery."
    },
    {
      eventTitle: "Beaulieu International Autojumble 2026",
      eventStartDateTime: "12092026:09:00:00",
      eventEndDateTime: "13092026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/international-autojumble/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Autojumble"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-international-autojumble-2026",
      eventFeatured: true,
      eventDescription: "Europe's largest autojumble, with 2,000+ stands selling everything from spares and tools to memorabilia, plus a classic car park and trade village."
    },
    {
      eventTitle: "Welsh Motorsport & Supercar Festival 2026",
      eventStartDateTime: "13092026:10:00:00",
      eventEndDateTime: "13092026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://pembreycircuit.co.uk/racing/welsh-motorsport-supercar-festival",
      eventAddress: "Pembrey Circuit, Pembrey, Llanelli, Carmarthenshire, SA16 0HZ",
      eventLat: 51.6986,
      eventLng: -4.2911,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Llanelli",
      eventPostalCode: "SA16 0HZ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Supercars", "Motoring Festival"],
      eventState: "Wales",
      eventSlug: "welsh-motorsport-supercar-festival-2026",
      eventFeatured: false,
      eventDescription: "Third running of the Welsh Motorsport & Supercar Festival, with classic car collections, supercar zones and motorsport machinery at the home of Welsh motorsport."
    },
    {
      eventTitle: "NSRA Hot Rod Drags 2026",
      eventStartDateTime: "18092026:10:00:00",
      eventEndDateTime: "20092026:22:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://santapod.co.uk/events/hot-rod-drags/",
      eventAddress: "Santa Pod Raceway, Airfield Road, Wellingborough, Northamptonshire, NN29 7XA",
      eventLat: 52.2519,
      eventLng: -0.5897,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Wellingborough",
      eventPostalCode: "NN29 7XA",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Hot Rods", "Nostalgia Racing"],
      eventState: "Northamptonshire",
      eventSlug: "nsra-hot-rod-drags-2026",
      eventFeatured: false,
      eventDescription: "37th NSRA Hot Rod Drags featuring nostalgia drag racing for pre-1973 cars, fireworks and live music."
    },
    {
      eventTitle: "Goodwood Revival 2026",
      eventStartDateTime: "18092026:07:30:00",
      eventEndDateTime: "20092026:19:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.goodwood.com/motorsport/goodwood-revival/",
      eventAddress: "Goodwood Motor Circuit, Chichester, West Sussex, PO18 0PH",
      eventLat: 50.8585,
      eventLng: -0.7508,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Chichester",
      eventPostalCode: "PO18 0PH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing", "Vintage Fashion"],
      eventState: "West Sussex",
      eventSlug: "goodwood-revival-2026",
      eventFeatured: true,
      eventDescription: "The world's only historic motor race meeting staged entirely in period dress, themed 'La Dolce Vita' in 2026 to celebrate Italian style and racing romance."
    },
    {
      eventTitle: "Sywell Classic — Pistons & Props 2026",
      eventStartDateTime: "26092026:09:00:00",
      eventEndDateTime: "27092026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.sywellaerodrome.co.uk/events/public-events/pistons-and-props/",
      eventAddress: "Sywell Aerodrome, Sywell, Northampton, Northamptonshire, NN6 0BN",
      eventLat: 52.3047,
      eventLng: -0.7917,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Northampton",
      eventPostalCode: "NN6 0BN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Aviation", "Vintage Festival"],
      eventState: "Northamptonshire",
      eventSlug: "sywell-classic-pistons-props-2026",
      eventFeatured: true,
      eventDescription: "Pre-1970s motoring and aviation festival at one of the UK's last grass aerodromes, with vintage fashion, military re-enactors and flying displays."
    },
    {
      eventTitle: "Beaulieu Simply Italian 2026",
      eventStartDateTime: "27092026:10:00:00",
      eventEndDateTime: "27092026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8181,
      eventLng: -1.4506,
      eventPhone: "01590 612345",
      eventEmail: "info@beaulieu.co.uk",
      eventCity: "Brockenhurst",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Italian Cars", "Club Show"],
      eventState: "Hampshire",
      eventSlug: "beaulieu-simply-italian-2026",
      eventFeatured: false,
      eventDescription: "Beaulieu's Simply Italian rally brings Fiats, Ferraris, Lancias, Alfa Romeos and more onto the New Forest lawns to close the Simply rally season."
    },

    // ---- OCTOBER 2026 ----
    {
      eventTitle: "Bicester Heritage October Scramble 2026",
      eventStartDateTime: "04102026:09:00:00",
      eventEndDateTime: "04102026:16:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://bicestermotion.com/scramble",
      eventAddress: "Bicester Motion, Buckingham Road, Bicester, Oxfordshire, OX27 8AL",
      eventLat: 51.9189,
      eventLng: -1.1483,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Bicester",
      eventPostalCode: "OX27 8AL",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Autojumble", "Family Event"],
      eventState: "Oxfordshire",
      eventSlug: "bicester-heritage-october-scramble-2026",
      eventFeatured: false,
      eventDescription: "Sunday Scramble at the former RAF Bicester with rally machines, homologation specials, vintage tractors and open workshop doors across the historic site."
    },
    {
      eventTitle: "HSCC Silverstone Finals Meeting 2026",
      eventStartDateTime: "31102026:09:00:00",
      eventEndDateTime: "01112026:17:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://hscc.org.uk/racing-calendar-2026/",
      eventAddress: "Silverstone Circuit, Towcester, Northamptonshire, NN12 8TN",
      eventLat: 52.0786,
      eventLng: -1.0169,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Towcester",
      eventPostalCode: "NN12 8TN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Historic Racing"],
      eventState: "Northamptonshire",
      eventSlug: "hscc-silverstone-finals-2026",
      eventFeatured: false,
      eventDescription: "HSCC's season-closing race meeting at the Silverstone National circuit with Formula Ford, Formula Junior, Historic Touring Cars and Historic Sports Cars."
    },

    // ---- NOVEMBER 2026 ----
    {
      eventTitle: "RM Sotheby's London to Brighton Veteran Car Run 2026",
      eventStartDateTime: "01112026:06:30:00",
      eventEndDateTime: "01112026:16:30:00",
      eventTicketPrice: "Free for spectators",
      eventWebsite: "https://www.veterancarrun.com/",
      eventAddress: "Hyde Park, London (start) to Madeira Drive, Brighton (finish)",
      eventLat: 51.5074,
      eventLng: -0.1657,
      eventPhone: "",
      eventEmail: "",
      eventCity: "London / Brighton",
      eventPostalCode: "W2 2UH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Veteran Cars", "Drive"],
      eventState: "London / Sussex",
      eventSlug: "london-to-brighton-veteran-car-run-2026",
      eventFeatured: true,
      eventDescription: "The world's longest-running motoring event, with 400+ pre-1905 veteran cars departing Hyde Park at sunrise on the 60-mile run to Brighton's seafront."
    },
    {
      eventTitle: "Lancaster Insurance Classic Motor Show — NEC Birmingham 2026",
      eventStartDateTime: "13112026:09:00:00",
      eventEndDateTime: "15112026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.necclassicmotorshow.com/",
      eventAddress: "NEC Birmingham, North Avenue, Marston Green, Birmingham, B40 1NT",
      eventLat: 52.4506,
      eventLng: -1.7180,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Birmingham",
      eventPostalCode: "B40 1NT",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Indoor Show", "Club Show"],
      eventState: "West Midlands",
      eventSlug: "nec-classic-motor-show-2026",
      eventFeatured: true,
      eventDescription: "The UK's biggest indoor classic show with 3,000+ cars and bikes, the world's largest gathering of car clubs and a packed live restoration and live stage programme."
    },

    // ========== ADDITIONAL OCTOBER 2026 ==========
    {
      eventTitle: "Classic Motorcycle Mechanics Show — Stafford 2026",
      eventStartDateTime: "10102026:09:00:00",
      eventEndDateTime: "11102026:17:00:00",
      eventTicketPrice: "From £16.50 advance (under-16s free)",
      eventWebsite: "https://www.classicbikeshows.com/staffordo/",
      eventAddress: "Staffordshire County Showground, Weston Road, Stafford, ST18 0BD",
      eventLat: 52.8087,
      eventLng: -2.0708,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Stafford",
      eventPostalCode: "ST18 0BD",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Motorcycles", "Indoor Show", "Autojumble"],
      eventState: "Staffordshire",
      eventSlug: "classic-motorcycle-mechanics-show-stafford-2026",
      eventFeatured: false,
      eventDescription: "The UK's largest indoor classic bike show, focused on 1970s–2000s machinery with club displays, traders, autojumble and the Bonhams Autumn Stafford motorcycle sale on site."
    },

    // ========== END OF OCTOBER / EARLY NOVEMBER WEEKEND ==========
    {
      eventTitle: "Classic & Sports Car — The London Show 2026",
      eventStartDateTime: "30102026:10:00:00",
      eventEndDateTime: "01112026:18:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.thelondonclassiccarshow.co.uk/",
      eventAddress: "Alexandra Palace, Alexandra Palace Way, London, N22 7AY",
      eventLat: 51.5961,
      eventLng: -0.1306,
      eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "N22 7AY",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Indoor Show", "Concours"],
      eventState: "Greater London",
      eventSlug: "classic-and-sports-car-london-show-2026",
      eventFeatured: false,
      eventDescription: "Three-day dealer and concours showcase at Alexandra Palace, timed to coincide with the Regent Street Motor Show and London to Brighton Veteran Car Run weekend."
    },
    {
      eventTitle: "Regent Street Motor Show 2026",
      eventStartDateTime: "31102026:10:30:00",
      eventEndDateTime: "31102026:16:00:00",
      eventTicketPrice: "Free",
      eventWebsite: "https://www.regentstreetmotorshow.com/",
      eventAddress: "Regent Street, Oxford Circus to Piccadilly Circus, London",
      eventLat: 51.5118,
      eventLng: -0.1397,
      eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "W1B 5AH",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Classic Cars", "Veteran Cars", "Family Event"],
      eventState: "Greater London",
      eventSlug: "regent-street-motor-show-2026",
      eventFeatured: true,
      eventDescription: "Free open-air display along a closed-off Regent Street covering 125 years of motoring, including the veteran cars heading out on the London to Brighton Run the following morning."
    },

    // ========== ADDITIONAL NOVEMBER 2026 ==========
    {
      eventTitle: "Simply Smart — Beaulieu 2026",
      eventStartDateTime: "08112026:10:00:00",
      eventEndDateTime: "08112026:16:00:00",
      eventTicketPrice: "See website",
      eventWebsite: "https://www.beaulieu.co.uk/events/simply-smart/",
      eventAddress: "National Motor Museum, Beaulieu, Brockenhurst, Hampshire, SO42 7ZN",
      eventLat: 50.8200,
      eventLng: -1.4530,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Beaulieu",
      eventPostalCode: "SO42 7ZN",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Smart Cars", "Marque-specific", "Club Show"],
      eventState: "Hampshire",
      eventSlug: "simply-smart-beaulieu-2026",
      eventFeatured: false,
      eventDescription: "Owners-club gathering of every generation of the Smart car on the lawn at the National Motor Museum, the late-season closer of Beaulieu's Simply marque-rally series."
    },
    {
      eventTitle: "International Historic Motoring Awards 2026",
      eventStartDateTime: "13112026:19:00:00",
      eventEndDateTime: "13112026:23:30:00",
      eventTicketPrice: "Black-tie ticketed (see website)",
      eventWebsite: "https://www.historicmotoringawards.com/",
      eventAddress: "The Peninsula London, 1 Grosvenor Place, London, SW1X 7HJ",
      eventLat: 51.5009,
      eventLng: -0.1525,
      eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "SW1X 7HJ",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Awards", "Industry"],
      eventState: "Greater London",
      eventSlug: "international-historic-motoring-awards-2026",
      eventFeatured: false,
      eventDescription: "Magneto and Octane's industry awards for the historic motoring world — restorations, events, publications and personalities of the year (provisional date; confirm with organiser nearer the event)."
    },
    {
      eventTitle: "Royal Automobile Club Historic Awards 2026",
      eventStartDateTime: "18112026:19:00:00",
      eventEndDateTime: "18112026:23:30:00",
      eventTicketPrice: "Member/guest tickets",
      eventWebsite: "https://royalautomobileclubhistoricawards.co.uk/",
      eventAddress: "Royal Automobile Club, 89 Pall Mall, London, SW1Y 5HS",
      eventLat: 51.5076,
      eventLng: -0.1330,
      eventPhone: "",
      eventEmail: "",
      eventCity: "London",
      eventPostalCode: "SW1Y 5HS",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Awards", "Industry"],
      eventState: "Greater London",
      eventSlug: "royal-automobile-club-historic-awards-2026",
      eventFeatured: false,
      eventDescription: "Annual dinner and ceremony recognising achievement in historic motorsport and motoring, held at the Pall Mall clubhouse (provisional date; check with the Club closer to November)."
    },
    {
      eventTitle: "RAC Rally of the Tests 2026",
      eventStartDateTime: "19112026:08:00:00",
      eventEndDateTime: "22112026:18:00:00",
      eventTicketPrice: "Spectating free at public stages; entry by competition",
      eventWebsite: "https://www.hero-era.com/rallies/2026/11/rac-rally-of-the-tests-2026",
      eventAddress: "Llandudno (start) — North & South Wales route",
      eventLat: 53.3236,
      eventLng: -3.8270,
      eventPhone: "",
      eventEmail: "",
      eventCity: "Llandudno",
      eventPostalCode: "LL30 2GA",
      eventCountryCode: "GB",
      eventImageUrl: "/assets/images/events/event-placeholder-brand.svg",
      eventCategory: ["Historic Rally", "Drive", "Multi-day"],
      eventState: "Conwy / Wales",
      eventSlug: "rac-rally-of-the-tests-2026",
      eventFeatured: false,
      eventDescription: "HERO-ERA's flagship four-day historic regularity rally — 24th edition — running classic cars across the lanes and stages of North and South Wales from a Llandudno headquarters."
    }
  ];
};
