backend:
  name: proxy
  proxy_url: http://localhost:5500/api
  branch: main

# When using the proxy backend, it is considered "local"
local_backend: true

# Enable the editorial workflow for drafts, review, and publishing
publish_mode: editorial_workflow
  
media_folder: "public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "clubs"
    label: "Clubs"
    folder: "src/_data/clubs-json"
    create: true
    slug: "{{slug}}"
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the title, lowercase with hyphens" }
      - { label: "ID", name: "id", widget: "number", hint: "Unique identifier for the club" }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "City", name: "city", widget: "string", required: false }
      - { label: "State/County", name: "state", widget: "string", required: false }
      - { label: "Postal Code", name: "postalCode", widget: "string", required: false }
      - { label: "Country Code", name: "countryCode", widget: "string", default: "GB" }
      - { label: "Category", name: "category", widget: "string", default: "Car Club" }
      - { label: "Image URL", name: "imageUrl", widget: "image", required: false, allow_multiple: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Description", name: "description", widget: "text", required: false }
  
  - name: "events"
    label: "Events"
    folder: "src/_data/events-json"
    create: true
    slug: "{{slug}}"
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Event Title", name: "eventTitle", widget: "string" }
      - { label: "Event Slug", name: "eventSlug", widget: "string", hint: "URL-friendly version of the title, lowercase with hyphens" }
      - { label: "Event Description", name: "eventDescription", widget: "text" }
      - { label: "Event Start Date/Time", name: "eventStartDateTime", widget: "string", hint: "Format: DDMMYYYY:HH:mm:ss (e.g., 08062025:10:00:00)" }
      - { label: "Event End Date/Time", name: "eventEndDateTime", widget: "string", hint: "Format: DDMMYYYY:HH:mm:ss (e.g., 08062025:16:00:00)" }
      - { label: "Event Ticket Price", name: "eventTicketPrice", widget: "string", required: false }
      - { label: "Event Website", name: "eventWebsite", widget: "string", required: false }
      - { label: "Event Address", name: "eventAddress", widget: "string", required: false }
      - { label: "Event Phone", name: "eventPhone", widget: "string", required: false }
      - { label: "Event Email", name: "eventEmail", widget: "string", required: false }
      - { label: "Event City", name: "eventCity", widget: "string", required: false }
      - { label: "Event State/County", name: "eventState", widget: "string", required: false }
      - { label: "Event Postal Code", name: "eventPostalCode", widget: "string", required: false }
      - { label: "Event Country Code", name: "eventCountryCode", widget: "string", default: "GB" }
      - { label: "Event Category", name: "eventCategory", widget: "list", required: false, hint: "One or more categories like 'Car Show', 'Truck Show'" }
      - { label: "Event Featured", name: "eventFeatured", widget: "boolean", default: false }
      - { label: "Event Image", name: "eventImageUrl", widget: "image", required: false, allow_multiple: false }